# Generated by Django 5.2.8 on 2026-09-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('email_domains', models.JSONField(blank=True, default=list)),
                ('reputation_tier', models.PositiveSmallIntegerField(choices=[(1, 'Elite'), (2, 'Strong'), (3, 'Standard'), (4, 'Basic'), (5, 'Self-claimed high'), (8, 'Self-claimed low'), (9, 'Unranked')], db_index=True, default=9)),
                ('reputation_source', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_count', models.PositiveIntegerField(default=0)),
                ('search_blob', models.CharField(blank=True, db_index=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('profession_tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['country', 'name'], name='catalog_emp_country_903724_idx'), models.Index(fields=['country', 'reputation_tier'], name='catalog_emp_country_326df3_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'name'), name='uniq_employer_country_name')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('email_domains', models.JSONField(blank=True, default=list)),
                ('reputation_tier', models.PositiveSmallIntegerField(choices=[(1, 'Elite'), (2, 'Strong'), (3, 'Standard'), (4, 'Basic'), (5, 'Self-claimed high'), (8, 'Self-claimed low'), (9, 'Unranked')], db_index=True, default=9)),
                ('reputation_source', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_count', models.PositiveIntegerField(default=0)),
                ('search_blob', models.CharField(blank=True, db_index=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('institute', 'Institute')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['country', 'name'], name='catalog_ins_country_84553d_idx'), models.Index(fields=['country', 'reputation_tier'], name='catalog_ins_country_f68ef2_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'name'), name='uniq_institution_country_name')],
            },
        ),
    ]
