# Generated by Django 5.2.8 on 2026-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profession_blob',
            field=models.CharField(blank=True, db_index=True, max_length=400),
        ),
    ]
