import { SelectIconOption } from "src/types/select";

export const CurrencyOptions: SelectIconOption[] = [
  { value: 'AED', label: 'AED', extra_label: 'UAE Dirham', icon: 'https://flagcdn.com/w20/ae.png' },
  { value: 'AFN', label: 'AFN', extra_label: 'Afghan Afghani', icon: 'https://flagcdn.com/w20/af.png' },
  { value: 'ALL', label: 'ALL', extra_label: 'Albanian Lek', icon: 'https://flagcdn.com/w20/al.png' },
  { value: 'AMD', label: 'AMD', extra_label: 'Armenian Dram', icon: 'https://flagcdn.com/w20/am.png' },
  { value: 'AOA', label: 'AOA', extra_label: 'Angolan Kwanza', icon: 'https://flagcdn.com/w20/ao.png' },
  { value: 'ARS', label: 'ARS', extra_label: 'Argentine Peso', icon: 'https://flagcdn.com/w20/ar.png' },
  { value: 'AUD', label: 'AUD', extra_label: 'Australian Dollar', icon: 'https://flagcdn.com/w20/au.png' },
  { value: 'BAM', label: 'BAM', extra_label: 'Bosnia-Herzegovina Mark', icon: 'https://flagcdn.com/w20/ba.png' },
  { value: 'BGN', label: 'BGN', extra_label: 'Bulgarian Lev', icon: 'https://flagcdn.com/w20/bg.png' },
  { value: 'BND', label: 'BND', extra_label: 'Brunei Dollar', icon: 'https://flagcdn.com/w20/bn.png' },
  { value: 'BRL', label: 'BRL', extra_label: 'Brazilian Real', icon: 'https://flagcdn.com/w20/br.png' },
  { value: 'BWP', label: 'BWP', extra_label: 'Botswanan Pula', icon: 'https://flagcdn.com/w20/bw.png' },
  { value: 'CDF', label: 'CDF', extra_label: 'Congolese Franc', icon: 'https://flagcdn.com/w20/cd.png' },
  { value: 'CHF', label: 'CHF', extra_label: 'Swiss Franc', icon: 'https://flagcdn.com/w20/ch.png' },
  { value: 'COP', label: 'COP', extra_label: 'Colombian Peso', icon: 'https://flagcdn.com/w20/co.png' },
  { value: 'CZK', label: 'CZK', extra_label: 'Czech Koruna', icon: 'https://flagcdn.com/w20/cz.png' },
  { value: 'DJF', label: 'DJF', extra_label: 'Djiboutian Franc', icon: 'https://flagcdn.com/w20/dj.png' },
  { value: 'DKK', label: 'DKK', extra_label: 'Danish Krone', icon: 'https://flagcdn.com/w20/dk.png' },
  { value: 'DZD', label: 'DZD', extra_label: 'Algerian Dinar', icon: 'https://flagcdn.com/w20/dz.png' },
  { value: 'EGP', label: 'EGP', extra_label: 'Egyptian Pound', icon: 'https://flagcdn.com/w20/eg.png' },
  { value: 'ERN', label: 'ERN', extra_label: 'Eritrean Nakfa', icon: 'https://flagcdn.com/w20/er.png' },
  { value: 'ETB', label: 'ETB', extra_label: 'Ethiopian Birr', icon: 'https://flagcdn.com/w20/et.png' },
  { value: 'EUR', label: 'EUR', extra_label: 'Euro', icon: 'https://flagcdn.com/w20/eu.png' },
  { value: 'GBP', label: 'GBP', extra_label: 'British Pound', icon: 'https://flagcdn.com/w20/gb.png' },
  { value: 'GEL', label: 'GEL', extra_label: 'Georgian Lari', icon: 'https://flagcdn.com/w20/ge.png' },
  { value: 'GHS', label: 'GHS', extra_label: 'Ghanaian Cedi', icon: 'https://flagcdn.com/w20/gh.png' },
  { value: 'GMD', label: 'GMD', extra_label: 'Gambian Dalasi', icon: 'https://flagcdn.com/w20/gm.png' },
  { value: 'GTQ', label: 'GTQ', extra_label: 'Guatemalan Quetzal', icon: 'https://flagcdn.com/w20/gt.png' },
  { value: 'HKD', label: 'HKD', extra_label: 'Hong Kong Dollar', icon: 'https://flagcdn.com/w20/hk.png' },
  { value: 'HNL', label: 'HNL', extra_label: 'Honduran Lempira', icon: 'https://flagcdn.com/w20/hn.png' },
  { value: 'HRK', label: 'HRK', extra_label: 'Croatian Kuna', icon: 'https://flagcdn.com/w20/hr.png' },
  { value: 'HUF', label: 'HUF', extra_label: 'Hungarian Forint', icon: 'https://flagcdn.com/w20/hu.png' },
  { value: 'IDR', label: 'IDR', extra_label: 'Indonesian Rupiah', icon: 'https://flagcdn.com/w20/id.png' },
  { value: 'INR', label: 'INR', extra_label: 'Indian Rupee', icon: 'https://flagcdn.com/w20/in.png' },
  { value: 'IQD', label: 'IQD', extra_label: 'Iraqi Dinar', icon: 'https://flagcdn.com/w20/iq.png' },
  { value: 'IRR', label: 'IRR', extra_label: 'Iranian Rial', icon: 'https://flagcdn.com/w20/ir.png' },
  { value: 'ISK', label: 'ISK', extra_label: 'Icelandic Króna', icon: 'https://flagcdn.com/w20/is.png' },
  { value: 'JOD', label: 'JOD', extra_label: 'Jordanian Dinar', icon: 'https://flagcdn.com/w20/jo.png' },
  { value: 'JPY', label: 'JPY', extra_label: 'Japanese Yen', icon: 'https://flagcdn.com/w20/jp.png' },
  { value: 'KES', label: 'KES', extra_label: 'Kenyan Shilling', icon: 'https://flagcdn.com/w20/ke.png' },
  { value: 'KRW', label: 'KRW', extra_label: 'South Korean Won', icon: 'https://flagcdn.com/w20/kr.png' },
  { value: 'KWD', label: 'KWD', extra_label: 'Kuwaiti Dinar', icon: 'https://flagcdn.com/w20/kw.png' },
  { value: 'KZT', label: 'KZT', extra_label: 'Kazakhstani Tenge', icon: 'https://flagcdn.com/w20/kz.png' },
  { value: 'LAK', label: 'LAK', extra_label: 'Lao Kip', icon: 'https://flagcdn.com/w20/la.png' },
  { value: 'MAD', label: 'MAD', extra_label: 'Moroccan Dirham', icon: 'https://flagcdn.com/w20/ma.png' },
  { value: 'MMK', label: 'MMK', extra_label: 'Myanmar Kyat', icon: 'https://flagcdn.com/w20/mm.png' },
  { value: 'MOP', label: 'MOP', extra_label: 'Macanese Pataca', icon: 'https://flagcdn.com/w20/mo.png' },
  { value: 'MVR', label: 'MVR', extra_label: 'Maldivian Rufiyaa', icon: 'https://flagcdn.com/w20/mv.png' },
  { value: 'MYR', label: 'MYR', extra_label: 'Malaysian Ringgit', icon: 'https://flagcdn.com/w20/my.png' },
  { value: 'MZN', label: 'MZN', extra_label: 'Mozambican Metical', icon: 'https://flagcdn.com/w20/mz.png' },
  { value: 'NAD', label: 'NAD', extra_label: 'Namibian Dollar', icon: 'https://flagcdn.com/w20/na.png' },
  { value: 'NGN', label: 'NGN', extra_label: 'Nigerian Naira', icon: 'https://flagcdn.com/w20/ng.png' },
  { value: 'NIO', label: 'NIO', extra_label: 'Nicaraguan Córdoba', icon: 'https://flagcdn.com/w20/ni.png' },
  { value: 'NOK', label: 'NOK', extra_label: 'Norwegian Krone', icon: 'https://flagcdn.com/w20/no.png' },
  { value: 'NPR', label: 'NPR', extra_label: 'Nepalese Rupee', icon: 'https://flagcdn.com/w20/np.png' },
  { value: 'NZD', label: 'NZD', extra_label: 'New Zealand Dollar', icon: 'https://flagcdn.com/w20/nz.png' },
  { value: 'OMR', label: 'OMR', extra_label: 'Omani Rial', icon: 'https://flagcdn.com/w20/om.png' },
  { value: 'PAB', label: 'PAB', extra_label: 'Panamanian Balboa', icon: 'https://flagcdn.com/w20/pa.png' },
  { value: 'PEN', label: 'PEN', extra_label: 'Peruvian Sol', icon: 'https://flagcdn.com/w20/pe.png' },
  { value: 'PHP', label: 'PHP', extra_label: 'Philippine Peso', icon: 'https://flagcdn.com/w20/ph.png' },
  { value: 'PKR', label: 'PKR', extra_label: 'Pakistani Rupee', icon: 'https://flagcdn.com/w20/pk.png' },
  { value: 'PLN', label: 'PLN', extra_label: 'Polish Złoty', icon: 'https://flagcdn.com/w20/pl.png' },
  { value: 'QAR', label: 'QAR', extra_label: 'Qatari Riyal', icon: 'https://flagcdn.com/w20/qa.png' },
  { value: 'RON', label: 'RON', extra_label: 'Romanian Leu', icon: 'https://flagcdn.com/w20/ro.png' },
  { value: 'RUB', label: 'RUB', extra_label: 'Russian Ruble', icon: 'https://flagcdn.com/w20/ru.png' },
  { value: 'RWF', label: 'RWF', extra_label: 'Rwandan Franc', icon: 'https://flagcdn.com/w20/rw.png' },
  { value: 'SAR', label: 'SAR', extra_label: 'Saudi Riyal', icon: 'https://flagcdn.com/w20/sa.png' },
  { value: 'SEK', label: 'SEK', extra_label: 'Swedish Krona', icon: 'https://flagcdn.com/w20/se.png' },
  { value: 'SGD', label: 'SGD', extra_label: 'Singapore Dollar', icon: 'https://flagcdn.com/w20/sg.png' },
  { value: 'THB', label: 'THB', extra_label: 'Thai Baht', icon: 'https://flagcdn.com/w20/th.png' },
  { value: 'TND', label: 'TND', extra_label: 'Tunisian Dinar', icon: 'https://flagcdn.com/w20/tn.png' },
  { value: 'TRY', label: 'TRY', extra_label: 'Turkish Lira', icon: 'https://flagcdn.com/w20/tr.png' },
  { value: 'TWD', label: 'TWD', extra_label: 'New Taiwan Dollar', icon: 'https://flagcdn.com/w20/tw.png' },
  { value: 'UAH', label: 'UAH', extra_label: 'Ukrainian Hryvnia', icon: 'https://flagcdn.com/w20/ua.png' },
  { value: 'USD', label: 'USD', extra_label: 'US Dollar', icon: 'https://flagcdn.com/w20/us.png' },
  { value: 'UYU', label: 'UYU', extra_label: 'Uruguayan Peso', icon: 'https://flagcdn.com/w20/uy.png' },
  { value: 'UZS', label: 'UZS', extra_label: 'Uzbekistani Som', icon: 'https://flagcdn.com/w20/uz.png' },
  { value: 'VES', label: 'VES', extra_label: 'Venezuelan Bolívar', icon: 'https://flagcdn.com/w20/ve.png' },
  { value: 'VND', label: 'VND', extra_label: 'Vietnamese Dong', icon: 'https://flagcdn.com/w20/vn.png' },
  { value: 'XAF', label: 'XAF', extra_label: 'Central African CFA Franc', icon: 'https://flagcdn.com/w20/cf.png' },
  { value: 'XCD', label: 'XCD', extra_label: 'East Caribbean Dollar', icon: 'https://flagcdn.com/w20/ai.png' },
  { value: 'XOF', label: 'XOF', extra_label: 'West African CFA Franc', icon: 'https://flagcdn.com/w20/bf.png' },
  { value: 'XPF', label: 'XPF', extra_label: 'CFP Franc', icon: 'https://flagcdn.com/w20/nc.png' },
  { value: 'YER', label: 'YER', extra_label: 'Yemeni Rial', icon: 'https://flagcdn.com/w20/ye.png' },
  { value: 'ZAR', label: 'ZAR', extra_label: 'South African Rand', icon: 'https://flagcdn.com/w20/za.png' },
  { value: 'ZMW', label: 'ZMW', extra_label: 'Zambian Kwacha', icon: 'https://flagcdn.com/w20/zm.png' },
  { value: 'ZWL', label: 'ZWL', extra_label: 'Zimbabwean Dollar', icon: 'https://flagcdn.com/w20/zw.png' },
];

export default CurrencyOptions;