# Generated by Django, then hand-edited. See the note below.
#
# `makemigrations` resolves MESSAGING_PARTICIPANT_MODEL and writes the concrete
# model - a concrete `to=` plus a dependency on the host app -
# straight into this file, hardcoding the host into an app whose entire point is
# that it does not know about one.
#
# Django only avoids this for AUTH_USER_MODEL because `auth.User` declares
# `swappable` in its Meta; a third-party setting gets no such treatment. So the
# generated FKs and dependency are replaced by their swappable equivalents by
# hand, exactly once, here.
#
# If you regenerate this migration, redo this edit. See apps/messaging/README.md.

# Originally generated by Django 5.2.8 on 2026-09-07 21:33

import django.db.models.deletion
from django.conf import settings
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.MESSAGING_PARTICIPANT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(blank=True, db_index=True, max_length=30)),
                ('context_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('participants_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=140)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('kind', models.CharField(default='text', max_length=20)),
                ('client_ref', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.MESSAGING_PARTICIPANT_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['conversation', '-id'], name='messaging_m_convers_ae4159_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_ref', ''), _negated=True), fields=('conversation', 'sender', 'client_ref'), name='uniq_message_client_ref')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.conversation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.MESSAGING_PARTICIPANT_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['participant', '-id'], name='messaging_p_partici_877da9_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'participant'), name='uniq_conversation_participant')],
            },
        ),
    ]
