// utils/professionOptions.ts
export const professionOptions = [
  { value: 'software_engineer', label: 'Software Engineer' },
  { value: 'doctor', label: 'Doctor' },
  { value: 'teacher', label: 'Teacher' },
  { value: 'business_analyst', label: 'Business Analyst' },
  { value: 'accountant', label: 'Accountant' },
  { value: 'civil_servant', label: 'Civil Servant' },
  { value: 'lawyer', label: 'Lawyer' },
  { value: 'architect', label: 'Architect' },
  { value: 'banker', label: 'Banker' },
  { value: 'entrepreneur', label: 'Entrepreneur' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'pilot', label: 'Pilot' },
  { value: 'police_officer', label: 'Police Officer' },
  { value: 'engineer', label: 'Engineer' },
  { value: 'scientist', label: 'Scientist' },
  { value: 'professor', label: 'Professor' },
  { value: 'graphic_designer', label: 'Graphic Designer' },
  { value: 'chef', label: 'Chef' },
  { value: 'journalist', label: 'Journalist' },
  { value: 'actor', label: 'Actor' },
  { value: 'fashion_designer', label: 'Fashion Designer' },
  { value: 'sales_manager', label: 'Sales Manager' },
  { value: 'marketing_manager', label: 'Marketing Manager' },
  { value: 'other', label: 'Other' },
];
