export const PROFILE_FOR_VALUES = ["son", "daughter", "brother", "sister", "self"] as const;

/**
 * Whose profile this is.
 *
 * Phrased from the registering person's point of view. The labels used to be
 * generated by capitalising the value, which gave a bare "Son" against a
 * question about who you are - reading as though you were the son rather than
 * the parent filling it in.
 */
export const PROFILE_FOR_LABELS: Record<(typeof PROFILE_FOR_VALUES)[number], string> = {
  son: "My son",
  daughter: "My daughter",
  brother: "My brother",
  sister: "My sister",
  self: "Myself",
};

export const PROFILE_FOR_OPTIONS = PROFILE_FOR_VALUES.map((value) => ({
  value,
  label: PROFILE_FOR_LABELS[value],
}));

export const LOOKING_FOR_VALUES = ["bride", "groom"] as const;

export const LOOKING_FOR_OPTIONS = LOOKING_FOR_VALUES.map((value) => ({
  value,
  label: value.charAt(0).toUpperCase() + value.slice(1),
}));

export const MANAGED_BY_VALUES = [
  "self",
  "parent",
  "sibling",
  "relative",
  "guardian",
  "friend",
] as const;

/**
 * Who will actually answer the messages.
 *
 * Only asked when the profile is for someone else - "Myself" answers it - and
 * pre-filled from `profile_for`, so for most people it is a confirmation rather
 * than a new question. It exists for the cases the five `profile_for` values
 * cannot express: a cousin, a guardian, a family friend.
 */
export const MANAGED_BY_OPTIONS = [
  { value: "parent", label: "Their parent" },
  { value: "sibling", label: "Their sibling" },
  { value: "relative", label: "A relative" },
  { value: "guardian", label: "Their guardian" },
  { value: "friend", label: "A friend" },
  { value: "self", label: "They manage it themselves" },
];

/** What `profile_for` implies, mirroring apps/profiles/managed_by.py. */
export const MANAGED_BY_DEFAULTS: Record<string, string> = {
  self: "self",
  son: "parent",
  daughter: "parent",
  brother: "sibling",
  sister: "sibling",
};

export const AGE_OPTIONS = Array.from({length: 43}, (_,i) => {
    const v = (18 + i).toString();
    return { value: v, label: v };
})
