"""
Django settings for vivaah4you project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path


def _env_list(name, default):
    """Comma-separated env var -> list, ignoring blanks."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# All three are environment-driven so a deployment can be secured without a
# code change. The fallbacks keep `service.bat vivaah4u-api server` working out
# of the box for local development.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-v@=!f1y#z)ee=^%n9&(mok(bq4z20i2*(g&bbaui64rfqvm11(",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]")

if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError(
        "DJANGO_SECRET_KEY must be set to a real secret when DEBUG is off."
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third party apps
    'corsheaders',  # For handling CORS
    'ninja',  # For Django Ninja
    'ninja_extra',
    'ninja_jwt',  # Optional for JWT translations, but recommended
    #internal apps
    'apps.auth_api', #For authentication APIs
    'apps.profiles',
    'apps.catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vivaah4you.urls'

CORS_ALLOWED_ORIGINS = _env_list(
    "DJANGO_CORS_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000",
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vivaah4you.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JSON Web Tokens
# django-ninja-jwt defaults to a 5 minute access token, which expires while a
# user is still filling in one step of the profile wizard. The frontend keeps
# the access token in an httpOnly cookie and silently refreshes it on 401
# (see apps/vivaah4you-web/src/lib/djangoFetch.ts), so these lifetimes and the
# cookie max-age in src/lib/auth.tsx are kept in sync.
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'UPDATE_LAST_LOGIN': True,
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'




# -------------------------------
# One-time passcodes
# -------------------------------

# How long an issued passcode stays valid, and how long before another may be
# requested for the same number.
OTP_TTL_SECONDS = int(os.environ.get("OTP_TTL_SECONDS", "300"))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get("OTP_RESEND_COOLDOWN_SECONDS", "30"))

# Development bypass: this code is accepted for any number, so the sign-up and
# login flows work with no SMS provider wired up. Set OTP_DEV_CODE to an empty
# string in any real deployment - that disables the bypass entirely and leaves
# only genuinely issued codes working.
OTP_DEV_CODE = os.environ.get("OTP_DEV_CODE", "8888" if DEBUG else "")

# Set to enable the "Continue with Google" button. Until then the UI renders it
# in a disabled state that explains it is not configured yet.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
