# Generated by Django 5.2.8 on 2025-11-24 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height_cm', models.PositiveIntegerField(help_text='Height in centimeters')),
                ('hometown', models.CharField(max_length=150)),
                ('current_residence', models.CharField(max_length=150)),
                ('about_me', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('partner_preferences', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Never Married', max_length=40)),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
