# Generated by Django 5.2.8 on 2026-02-06 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_firstname_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob_change_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_change_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_display_picture_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_profile_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_change_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Joint'), (1, 'Nuclear'), (2, 'Extended')], default=0),
        ),
    ]
