# Generated by Django 5.2.8 on 2026-02-06 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_dob_change_count_profile_gender_change_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completeness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='astrology_belief',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_physique',
            field=models.PositiveIntegerField(default=0, help_text='1-10 scale for body physique', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Nuclear'), (1, 'Joint'), (2, 'Extended')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manglik_level',
            field=models.PositiveIntegerField(choices=[(0, "I don't know"), (1, 'No'), (2, 'Anshik/Partial'), (3, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Never Married'), (1, 'Married'), (2, 'Divorced'), (3, 'Widowed'), (4, 'Annulled'), (5, 'Awaiting Divorce')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religiousness',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
