# Generated by Django 5.2.8 on 2026-02-06 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_profile_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name_change_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
