# Generated by Django 5.2.8 on 2026-08-23 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_occupation_profile_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='employed_in',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('bride', 'Bride'), ('groom', 'Groom')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_for',
            field=models.CharField(blank=True, choices=[('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('self', 'Self')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_physique',
            field=models.CharField(blank=True, help_text='slim / normal / athletic / chubby / heavy', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exercise_habits',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
