# Generated by Django 5.2.8 on 2026-08-29 23:16

from django.db import migrations, models


def grandfather_existing_profiles(apps, schema_editor):
    """Treat everyone who registered before passcodes existed as verified.

    The column defaults to False, and password login is refused while it is
    False - without this every existing account would be locked out with no way
    to get a code, since their sign-up never issued one.
    """
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.update(phone_verified=True)


def unverify_all(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.update(phone_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_about_me_profile_brothers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_profiles, unverify_all),
    ]
