# Generated by Django 5.2.8 on 2026-08-30 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to='profiles.profile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_made', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['viewed', '-created_at'], name='profiles_pr_viewed__2461de_idx')],
            },
        ),
    ]
