# Generated by Django 5.2.8 on 2026-09-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edu_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_dob_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_name_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not verified'), (1, 'Contact verified'), (2, 'Profile complete'), (3, 'Identity verified')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
