# Generated by Django 5.2.8 on 2026-09-05 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_employer_profession_blob'),
        ('profiles', '0017_backfill_partner_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_reputation_tier',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_relocate_after_marriage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_settle_abroad',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='settle_abroad',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(max_length=40)),
                ('field_of_study', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('institution_country', models.CharField(blank=True, max_length=2)),
                ('is_other', models.BooleanField(default=False)),
                ('reputation_claimed', models.BooleanField(default=False)),
                ('completion_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.institution')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
