# Generated by Django 5.2.8 on 2026-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_backfill_education_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests_books',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_cuisines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_movies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_music',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests_travel',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
