# Generated by Django 5.2.8 on 2026-09-05 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_employer_profession_blob'),
        ('profiles', '0021_recompute_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.employer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer_reputation_tier',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='visa_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
