# Generated by Django 5.2.8 on 2026-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_employer_profile_employer_is_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='managed_by',
            field=models.CharField(blank=True, choices=[('self', 'The member'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('guardian', 'Guardian'), ('friend', 'Friend')], max_length=20),
        ),
    ]
