# Generated by Django 5.2.8 on 2026-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_alter_profile_partner_relocate_after_marriage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizenship_country',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
