# Generated by Django 5.2.8 on 2026-09-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_profile_citizenship_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
