# Generated by Django 5.2.8 on 2026-09-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_profile_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_matches_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='profiles.profile')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['blocked', 'blocker'], name='profiles_bl_blocked_fcbf9c_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_block')],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting a reply'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn by the sender')], default='pending', max_length=12)),
                ('pair_key', models.CharField(db_index=True, editable=False, max_length=40)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', 'status', '-created_at'], name='profiles_in_receive_ab8dc3_idx'), models.Index(fields=['sender', 'status', '-created_at'], name='profiles_in_sender__1bab46_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver'), name='uniq_interest_direction'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('pair_key',), name='uniq_live_interest_per_pair'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='interest_not_self')],
            },
        ),
    ]
