# Generated by Django 5.2.8 on 2026-09-09 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_profile_last_seen_matches_at_block_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=80)),
                ('about', models.CharField(blank=True, max_length=140)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='family_photos/')),
                ('is_married', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='profiles.profile')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['profile', 'position'], name='profiles_fa_profile_b4334c_idx')],
            },
        ),
    ]
