# Generated by Django 5.2.8 on 2026-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partner_drinking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_religiosities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_smoking',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
