# Generated by Django 5.2.8 on 2026-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_clear_interest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_living_in_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='identity_edits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_of_birth_state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
