import { SelectOption } from "@lokesh-workspace/ui";

/**
 * Professions.
 *
 * The original 25 forced most members into "Engineer", "Other", or a title that
 * was not really theirs. These are grouped by field and ordered roughly by how
 * common they are on Indian matrimonial profiles, since SelectDropdown renders
 * array order.
 *
 * Every original value is preserved, so no stored answer is orphaned. Values are
 * stable slugs and also key the employer catalog's `profession_tags`.
 */
export  const professionOptions: SelectOption[] = [
  // Software & data
  { value: 'software_engineer', label: 'Software Engineer', group: 'Technology & Data' },
  { value: 'data_scientist', label: 'Data Scientist / Analyst', group: 'Technology & Data' },
  { value: 'devops_engineer', label: 'DevOps / Cloud Engineer', group: 'Technology & Data' },
  { value: 'qa_engineer', label: 'QA / Test Engineer', group: 'Technology & Data' },
  { value: 'product_manager', label: 'Product Manager', group: 'Technology & Data' },
  { value: 'ux_designer', label: 'UX / Product Designer', group: 'Technology & Data' },
  { value: 'it_support', label: 'IT Support / Admin', group: 'Technology & Data' },
  { value: 'cybersecurity', label: 'Cybersecurity Specialist', group: 'Technology & Data' },
  { value: 'ml_engineer', label: 'Machine Learning Engineer', group: 'Technology & Data' },
  { value: 'data_engineer', label: 'Data Engineer', group: 'Technology & Data' },
  { value: 'mobile_developer', label: 'Mobile App Developer', group: 'Technology & Data' },
  { value: 'systems_analyst', label: 'Systems Analyst', group: 'Technology & Data' },
  { value: 'database_administrator', label: 'Database Administrator', group: 'Technology & Data' },
  { value: 'network_engineer', label: 'Network Engineer', group: 'Technology & Data' },
  { value: 'scrum_master', label: 'Scrum Master / Delivery Lead', group: 'Technology & Data' },
  { value: 'technical_writer', label: 'Technical Writer', group: 'Technology & Data' },

  // Engineering
  { value: 'engineer', label: 'Engineer (other)', group: 'Engineering' },
  { value: 'civil_engineer', label: 'Civil Engineer', group: 'Engineering' },
  { value: 'mechanical_engineer', label: 'Mechanical Engineer', group: 'Engineering' },
  { value: 'electrical_engineer', label: 'Electrical Engineer', group: 'Engineering' },
  { value: 'chemical_engineer', label: 'Chemical Engineer', group: 'Engineering' },
  { value: 'architect', label: 'Architect', group: 'Engineering' },
  { value: 'electronics_engineer', label: 'Electronics Engineer', group: 'Engineering' },
  { value: 'aerospace_engineer', label: 'Aerospace Engineer', group: 'Engineering' },
  { value: 'automobile_engineer', label: 'Automobile Engineer', group: 'Engineering' },
  { value: 'production_engineer', label: 'Production / Industrial Engineer', group: 'Engineering' },
  { value: 'quality_engineer', label: 'Quality Assurance Engineer', group: 'Engineering' },
  { value: 'site_engineer', label: 'Site / Project Engineer', group: 'Engineering' },
  { value: 'marine_engineer', label: 'Marine Engineer', group: 'Engineering' },
  { value: 'mining_engineer', label: 'Mining / Metallurgy Engineer', group: 'Engineering' },

  // Medicine & health
  { value: 'doctor', label: 'Doctor / Physician', group: 'Medicine & Health' },
  { value: 'surgeon', label: 'Surgeon', group: 'Medicine & Health' },
  { value: 'dentist', label: 'Dentist', group: 'Medicine & Health' },
  { value: 'nurse', label: 'Nurse', group: 'Medicine & Health' },
  { value: 'pharmacist', label: 'Pharmacist', group: 'Medicine & Health' },
  { value: 'physiotherapist', label: 'Physiotherapist', group: 'Medicine & Health' },
  { value: 'veterinarian', label: 'Veterinarian', group: 'Medicine & Health' },
  { value: 'psychologist', label: 'Psychologist / Therapist', group: 'Medicine & Health' },
  { value: 'medical_researcher', label: 'Medical Researcher', group: 'Medicine & Health' },
  { value: 'ayurvedic_doctor', label: 'Ayurvedic / Homeopathic Doctor', group: 'Medicine & Health' },
  { value: 'radiologist', label: 'Radiologist', group: 'Medicine & Health' },
  { value: 'pathologist', label: 'Pathologist', group: 'Medicine & Health' },
  { value: 'anaesthetist', label: 'Anaesthetist', group: 'Medicine & Health' },
  { value: 'paediatrician', label: 'Paediatrician', group: 'Medicine & Health' },
  { value: 'gynaecologist', label: 'Gynaecologist', group: 'Medicine & Health' },
  { value: 'optometrist', label: 'Optometrist', group: 'Medicine & Health' },
  { value: 'dietitian', label: 'Dietitian / Nutritionist', group: 'Medicine & Health' },
  { value: 'lab_technician', label: 'Medical Lab Technician', group: 'Medicine & Health' },
  { value: 'paramedic', label: 'Paramedic / Emergency Care', group: 'Medicine & Health' },

  // Finance, law & consulting
  { value: 'chartered_accountant', label: 'Chartered Accountant', group: 'Banking, Finance & Law' },
  { value: 'accountant', label: 'Accountant', group: 'Banking, Finance & Law' },
  { value: 'banker', label: 'Banker', group: 'Banking, Finance & Law' },
  { value: 'investment_professional', label: 'Investment / Finance Professional', group: 'Banking, Finance & Law' },
  { value: 'consultant', label: 'Consultant', group: 'Banking, Finance & Law' },
  { value: 'business_analyst', label: 'Business Analyst', group: 'Banking, Finance & Law' },
  { value: 'lawyer', label: 'Lawyer / Advocate', group: 'Banking, Finance & Law' },
  { value: 'company_secretary', label: 'Company Secretary', group: 'Banking, Finance & Law' },
  { value: 'actuary', label: 'Actuary', group: 'Banking, Finance & Law' },
  { value: 'auditor', label: 'Auditor', group: 'Banking, Finance & Law' },
  { value: 'cost_accountant', label: 'Cost / Management Accountant', group: 'Banking, Finance & Law' },
  { value: 'financial_analyst', label: 'Financial Analyst', group: 'Banking, Finance & Law' },
  { value: 'investment_banker', label: 'Investment Banker', group: 'Banking, Finance & Law' },
  { value: 'wealth_manager', label: 'Wealth / Portfolio Manager', group: 'Banking, Finance & Law' },
  { value: 'insurance_professional', label: 'Insurance Professional', group: 'Banking, Finance & Law' },
  { value: 'tax_consultant', label: 'Tax Consultant', group: 'Banking, Finance & Law' },
  { value: 'judge', label: 'Judge / Judicial Officer', group: 'Banking, Finance & Law' },
  { value: 'legal_advisor', label: 'Legal Advisor / Counsel', group: 'Banking, Finance & Law' },
  { value: 'paralegal', label: 'Paralegal', group: 'Banking, Finance & Law' },

  // Government & services
  { value: 'civil_servant', label: 'Civil Servant (IAS / IPS / IFS)', group: 'Government & Services' },
  { value: 'government_employee', label: 'Government Employee', group: 'Government & Services' },
  { value: 'police_officer', label: 'Police Officer', group: 'Government & Services' },
  { value: 'defence', label: 'Armed Forces', group: 'Government & Services' },
  { value: 'pilot', label: 'Pilot', group: 'Government & Services' },
  { value: 'cabin_crew', label: 'Cabin Crew', group: 'Government & Services' },
  { value: 'merchant_navy', label: 'Merchant Navy', group: 'Government & Services' },
  { value: 'air_traffic_controller', label: 'Air Traffic Controller', group: 'Government & Services' },
  { value: 'railway_employee', label: 'Railway Services', group: 'Government & Services' },
  { value: 'customs_officer', label: 'Customs / Excise Officer', group: 'Government & Services' },
  { value: 'firefighter', label: 'Firefighter', group: 'Government & Services' },
  { value: 'diplomat', label: 'Diplomat / Foreign Service', group: 'Government & Services' },
  { value: 'postal_services', label: 'Postal Services', group: 'Government & Services' },

  // Education & research
  { value: 'teacher', label: 'Teacher', group: 'Education & Research' },
  { value: 'professor', label: 'Professor / Lecturer', group: 'Education & Research' },
  { value: 'scientist', label: 'Scientist / Researcher', group: 'Education & Research' },
  { value: 'principal', label: 'Principal / Head of School', group: 'Education & Research' },
  { value: 'school_counsellor', label: 'School Counsellor', group: 'Education & Research' },
  { value: 'special_educator', label: 'Special Educator', group: 'Education & Research' },
  { value: 'librarian', label: 'Librarian / Archivist', group: 'Education & Research' },
  { value: 'tutor', label: 'Private Tutor / Coaching', group: 'Education & Research' },
  { value: 'research_associate', label: 'Research Associate', group: 'Education & Research' },

  // Business & operations
  { value: 'entrepreneur', label: 'Entrepreneur / Founder', group: 'Business & Operations' },
  { value: 'business_owner', label: 'Business Owner', group: 'Business & Operations' },
  { value: 'sales_manager', label: 'Sales Manager', group: 'Business & Operations' },
  { value: 'marketing_manager', label: 'Marketing Manager', group: 'Business & Operations' },
  { value: 'hr_professional', label: 'HR Professional', group: 'Business & Operations' },
  { value: 'operations_manager', label: 'Operations Manager', group: 'Business & Operations' },
  { value: 'supply_chain', label: 'Supply Chain / Logistics', group: 'Business & Operations' },
  { value: 'real_estate', label: 'Real Estate Professional', group: 'Business & Operations' },
  { value: 'project_manager', label: 'Project Manager', group: 'Business & Operations' },
  { value: 'account_manager', label: 'Account / Client Manager', group: 'Business & Operations' },
  { value: 'procurement', label: 'Procurement / Purchasing', group: 'Business & Operations' },
  { value: 'retail_manager', label: 'Retail Manager', group: 'Business & Operations' },
  { value: 'hospitality_manager', label: 'Hotel / Hospitality Manager', group: 'Business & Operations' },
  { value: 'event_manager', label: 'Event Manager', group: 'Business & Operations' },
  { value: 'travel_professional', label: 'Travel / Tourism Professional', group: 'Business & Operations' },
  { value: 'customer_success', label: 'Customer Success / Support', group: 'Business & Operations' },

  // Creative & media
  { value: 'graphic_designer', label: 'Graphic Designer', group: 'Creative & Media' },
  { value: 'fashion_designer', label: 'Fashion Designer', group: 'Creative & Media' },
  { value: 'interior_designer', label: 'Interior Designer', group: 'Creative & Media' },
  { value: 'journalist', label: 'Journalist', group: 'Creative & Media' },
  { value: 'content_creator', label: 'Content Creator / Writer', group: 'Creative & Media' },
  { value: 'photographer', label: 'Photographer / Videographer', group: 'Creative & Media' },
  { value: 'actor', label: 'Actor / Performer', group: 'Creative & Media' },
  { value: 'musician', label: 'Musician', group: 'Creative & Media' },
  { value: 'chef', label: 'Chef', group: 'Creative & Media' },
  { value: 'animator', label: 'Animator / VFX Artist', group: 'Creative & Media' },
  { value: 'film_maker', label: 'Film Maker / Director', group: 'Creative & Media' },
  { value: 'editor', label: 'Editor / Publisher', group: 'Creative & Media' },
  { value: 'copywriter', label: 'Copywriter', group: 'Creative & Media' },
  { value: 'radio_tv', label: 'Radio / TV Professional', group: 'Creative & Media' },
  { value: 'makeup_artist', label: 'Makeup Artist / Stylist', group: 'Creative & Media' },
  { value: 'art_director', label: 'Art Director', group: 'Creative & Media' },

  // Other paths
  { value: 'agriculture', label: 'Agriculture / Farming', group: 'Other paths' },
  { value: 'social_worker', label: 'Social Worker / NGO', group: 'Other paths' },
  { value: 'sportsperson', label: 'Sportsperson / Coach', group: 'Other paths' },
  { value: 'fitness_trainer', label: 'Fitness Trainer / Yoga Instructor', group: 'Other paths' },
  { value: 'religious_vocation', label: 'Religious / Spiritual Vocation', group: 'Other paths' },
  { value: 'defence_civilian', label: 'Defence Civilian Services', group: 'Other paths' },
  { value: 'freelance_professional', label: 'Freelance Professional', group: 'Other paths' },
  { value: 'preparing_for_exams', label: 'Preparing for competitive exams', group: 'Other paths' },
  { value: 'homemaker', label: 'Homemaker', group: 'Other paths' },
  { value: 'student_profession', label: 'Student', group: 'Other paths' },
  { value: 'between_jobs', label: 'Between jobs', group: 'Other paths' },
  { value: 'retired', label: 'Retired', group: 'Other paths' },
  { value: 'other', label: 'Other', group: 'Other paths' },
];

export const employedInOptions: SelectOption[] = [
    { value: 'government', label: 'Government' },
    { value: 'private', label: 'Private' },
    { value: 'public_sector', label: 'Public Sector' },
    { value: 'self_employed', label: 'Self Employed' },
    { value: 'business', label: 'Business' },
    { value: 'student', label: 'Student' },
    { value: 'not_employed', label: 'Not Employed' },
    { value: 'other', label: 'Other' },
  ];

export const employedAsOptions: SelectOption[] = [
    { value: 'owner', label: 'Owner / Proprietor' },
    { value: 'partner', label: 'Partner' },
    { value: 'senior_management', label: 'Senior Management' },
    { value: 'middle_management', label: 'Middle Management' },
    { value: 'junior', label: 'Junior / Executive' },
    { value: 'entry_level', label: 'Entry Level' },
    { value: 'freelancer', label: 'Freelancer / Consultant' },
    { value: 'student', label: 'Student' },
    { value: 'other', label: 'Other' },
  ];

  export const educationOptions: SelectOption[] = [
  { value: 'high_school', label: 'High School' },
  { value: 'diploma', label: 'Diploma' },
  { value: 'bachelors', label: "Bachelor's" },
  { value: 'masters', label: "Master's" },
  { value: 'phd', label: 'PhD' },
  { value: 'professional', label: 'Professional Degree' },
  { value: 'other', label: 'Other' },
];

/**
 * Fields of study.
 *
 * The original eleven entries were so broad that most graduates had to answer
 * "Engineering" or "Other", which told a reader nothing. These are grouped by
 * discipline and ordered roughly by how common they are on Indian matrimonial
 * profiles, since SelectDropdown renders array order.
 *
 * The original eleven values are all preserved, so no stored answer is orphaned.
 */
export const fieldOfStudyOptions: SelectOption[] = [
  // Engineering & technology
  { value: 'computer_science', label: 'Computer Science / IT' },
  { value: 'engineering', label: 'Engineering (general)' },
  { value: 'electronics_engineering', label: 'Electronics / Electrical Engineering' },
  { value: 'mechanical_engineering', label: 'Mechanical Engineering' },
  { value: 'civil_engineering', label: 'Civil Engineering' },
  { value: 'chemical_engineering', label: 'Chemical Engineering' },
  { value: 'aerospace_engineering', label: 'Aerospace Engineering' },
  { value: 'biotechnology', label: 'Biotechnology / Bioengineering' },
  { value: 'data_science', label: 'Data Science / Analytics' },

  // Medicine & health
  { value: 'medicine', label: 'Medicine (MBBS / MD)' },
  { value: 'dentistry', label: 'Dentistry' },
  { value: 'pharmacy', label: 'Pharmacy' },
  { value: 'nursing', label: 'Nursing' },
  { value: 'physiotherapy', label: 'Physiotherapy' },
  { value: 'ayurveda_homeopathy', label: 'Ayurveda / Homeopathy / Unani' },
  { value: 'veterinary', label: 'Veterinary Science' },
  { value: 'public_health', label: 'Public Health' },

  // Business & commerce
  { value: 'management', label: 'Management / MBA' },
  { value: 'commerce', label: 'Commerce' },
  { value: 'accounting_finance', label: 'Accounting / Finance' },
  { value: 'economics', label: 'Economics' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'hospitality', label: 'Hotel Management / Hospitality' },

  // Sciences
  { value: 'science', label: 'Science (general)' },
  { value: 'physics', label: 'Physics' },
  { value: 'chemistry', label: 'Chemistry' },
  { value: 'mathematics', label: 'Mathematics / Statistics' },
  { value: 'biology', label: 'Biology / Life Sciences' },
  { value: 'environmental_science', label: 'Environmental Science' },
  { value: 'agriculture', label: 'Agriculture' },

  // Arts, law & social sciences
  { value: 'arts', label: 'Arts / Humanities' },
  { value: 'law', label: 'Law' },
  { value: 'psychology', label: 'Psychology' },
  { value: 'sociology', label: 'Sociology / Social Work' },
  { value: 'political_science', label: 'Political Science / Public Policy' },
  { value: 'journalism', label: 'Journalism / Mass Communication' },
  { value: 'literature', label: 'Literature / Languages' },
  { value: 'history', label: 'History / Archaeology' },

  // Creative & applied
  { value: 'design', label: 'Design' },
  { value: 'architecture', label: 'Architecture' },
  { value: 'fine_arts', label: 'Fine Arts / Performing Arts' },
  { value: 'fashion', label: 'Fashion / Textile' },
  { value: 'education', label: 'Education / Teaching' },

  { value: 'other', label: 'Other' },
];

export const collegeOptions: SelectOption[] = [
  { value: 'indian_institute_of_science_bangalore', label: 'Indian Institute of Science (Bangalore)' },
  { value: 'iit_bombay', label: 'IIT Bombay' },
  { value: 'iit_delhi', label: 'IIT Delhi' },
  { value: 'iit_madras', label: 'IIT Madras' },
  { value: 'iit_kanpur', label: 'IIT Kanpur' },
  { value: 'iit_kharagpur', label: 'IIT Kharagpur' },
  { value: 'iit_roorkee', label: 'IIT Roorkee' },
  { value: 'iit_guwahati', label: 'IIT Guwahati' },
  { value: 'iit_hyderabad', label: 'IIT Hyderabad' },
  { value: 'iit_bhu_varanasi', label: 'IIT (BHU) Varanasi' },
  { value: 'iisc_bangalore', label: 'IISc Bangalore' },
  { value: 'bits_pilani', label: 'BITS Pilani' },
  { value: 'bits_goa', label: 'BITS Goa' },
  { value: 'bits_hyderabad', label: 'BITS Hyderabad' },
  { value: 'nit_trichy', label: 'NIT Trichy' },
  { value: 'nit_surathkal', label: 'NIT Surathkal' },
  { value: 'nit_warangal', label: 'NIT Warangal' },
  { value: 'nit_calicut', label: 'NIT Calicut' },
  { value: 'nit_rourkela', label: 'NIT Rourkela' },
  { value: 'delhi_university', label: 'University of Delhi' },
  { value: 'st_stephens_college', label: "St. Stephen's College, Delhi" },
  { value: 'hindu_college', label: 'Hindu College (DU)' },
  { value: 'miranda_house', label: 'Miranda House (DU)' },
  { value: 'jawaharlal_nehru_university', label: 'Jawaharlal Nehru University' },
  { value: 'jamia_millia_islamia', label: 'Jamia Millia Islamia' },
  { value: 'banaras_hindu_university', label: 'Banaras Hindu University' },
  { value: 'university_of_calcutta', label: 'University of Calcutta' },
  { value: 'university_of_mumbai', label: 'University of Mumbai' },
  { value: 'anna_university', label: 'Anna University' },
  { value: 'university_of_hyderabad', label: 'University of Hyderabad' },
  { value: 'aligarh_muslim_university', label: 'Aligarh Muslim University' },
  { value: 'savitribai_phule_pune_university', label: 'Savitribai Phule Pune University' },
  { value: 'amrita_vishwa_vidyapeetham', label: 'Amrita Vishwa Vidyapeetham' },
  { value: 'vit_vellore', label: 'VIT Vellore' },
  { value: 'manipal_academy', label: 'Manipal Academy of Higher Education' },
  { value: 'srM_university', label: 'SRM University' },
  { value: 'pes_university', label: 'PES University' },
  { value: 'xlri_jamshedpur', label: 'XLRI Jamshedpur' },
  { value: 'iim_ahmedabad', label: 'IIM Ahmedabad' },
  { value: 'iim_bangalore', label: 'IIM Bangalore' },
  { value: 'iim_calcutta', label: 'IIM Calcutta' },
  { value: 'iim_lucknow', label: 'IIM Lucknow' },
  { value: 'iim_kozhikode', label: 'IIM Kozhikode' },
  { value: 'iim_indore', label: 'IIM Indore' },
  { value: 'tata_institute_of_social_sciences', label: 'TISS' },
  { value: 'tata_institute_of_fundamental_research', label: 'TIFR' },
  { value: 'indian_statistical_institute', label: 'Indian Statistical Institute (ISI)' },
  { value: 'national_law_school_bangalore', label: 'National Law School of India University (NLSIU)' },
  { value: 'nalsar_university', label: 'NALSAR University of Law' },
  { value: 'aiims_new_delhi', label: 'AIIMS New Delhi' },
  { value: 'king_george_medical_university', label: 'King George Medical University' },
  { value: 'christ_university', label: 'Christ University' },
  { value: 'st_xaviers_college_mumbai', label: 'St. Xavier’s College, Mumbai' },
  { value: 'st_xaviers_college_kolkata', label: 'St. Xavier’s College, Kolkata' },
  { value: 'lady_shriram_college', label: 'Lady Shri Ram College (LSR)' },
  { value: 'christian_medical_college', label: 'Christian Medical College (Vellore)' },
  { value: 'kakatiya_university', label: 'Kakatiya University' },
  { value: 'annamalai_university', label: 'Annamalai University' },
  { value: 'kurukshetra_university', label: 'Kurukshetra University' },
  { value: 'gautam_buddha_university', label: 'Gautam Buddha University' },
  { value: 'bhopal_university', label: 'Bhopal University' },
  { value: 'mahatma_gandhi_university', label: 'Mahatma Gandhi University' },
  { value: 'kerala_university', label: 'University of Kerala' },
  { value: 'rajasthan_university', label: 'University of Rajasthan' },
  { value: 'calicut_university', label: 'University of Calicut' },
  { value: 'manipur_university', label: 'Manipur University' },
  { value: 'north_eastern_hill_university', label: 'NEHU' },
  { value: 'bose_institute', label: 'Bose Institute' },
  { value: 'srm_university_chennai', label: 'SRM Institute of Science and Technology' },
  { value: 'amity_university_noida', label: 'Amity University, Noida' },
  { value: 'shri_ram_college_of_commerce', label: 'SRCC (Shri Ram College of Commerce)' },
  { value: 'ips_academy', label: 'IPS Academy' },
  { value: 'law_college_bombay', label: 'Government Law College, Mumbai' },
  { value: 'fms_delhi', label: 'FMS Delhi' },
  { value: 'nift_delhi', label: 'NIFT' },
  { value: 'national_institute_of_design', label: 'NID' },
  { value: 'islami_universities', label: 'Various Islamic Universities' },
  { value: 'pondi_university', label: 'Pondicherry University' },
  { value: 'ciiit', label: 'CIIT' },
  { value: 'manipalinstitute', label: 'Manipal Institute' },
  { value: 'other_college', label: 'Other / Not Listed' },
];
