export const communitiesByReligion: { [key: string]: { value: string; label: string }[] } = {
  hindu: [
    { value: 'adi_andhra', label: 'Adi Andhra' },
    { value: 'adi_dravida', label: 'Adi Dravida' },
    { value: 'adi_karnataka', label: 'Adi Karnataka' },
    { value: 'agamudayar', label: 'Agamudayar' },
    { value: 'agri', label: 'Agri' },
    { value: 'ad_dharmi', label: 'Ad Dharmi' },
    { value: 'ahir', label: 'Ahir' },
    { value: 'ahir_ahir_shimpi', label: 'Ahir-Ahir shimpi' },
    { value: 'ahirwar', label: 'Ahirwar' },
    { value: 'ahom', label: 'Ahom' },
    { value: 'ambalavasi', label: 'Ambalavasi' },
    { value: 'ambalavasi_pisharody', label: 'Ambalavasi-Pisharody' },
    { value: 'ambalavasi_poduval', label: 'Ambalavasi-Poduval' },
    { value: 'amma_kodava', label: 'Amma Kodava' },
    { value: 'arakh_arakvanshiya', label: 'Arakh Arakvanshiya' },
    { value: 'arekatica', label: 'Arekatica' },
    { value: 'arunthathiyar', label: 'Arunthathiyar' },
    { value: 'arya_vysya', label: 'Arya Vysya' },
    { value: 'ayyaraka', label: 'Ayyaraka' },
    { value: 'badaga', label: 'Badaga' },
    { value: 'badhai', label: 'Badhai' },
    { value: 'bagdi', label: 'Bagdi' },
    { value: 'baghel_gaderiya', label: 'Baghel Gaderiya' },
    { value: 'bahi', label: 'Bahi' },
    { value: 'baidya', label: 'Baidya' },
    { value: 'bairwa', label: 'Bairwa' },
    { value: 'baishnab', label: 'Baishnab' },
    { value: 'baishya', label: 'Baishya' },
    { value: 'baishya_saha', label: 'Baishya-Saha' },
    { value: 'bania_all', label: 'Bania All' },
    { value: 'baishya_kapali', label: 'Baishya Kapali' },
    { value: 'bajantri', label: 'Bajantri' },
    { value: 'balai', label: 'Balai' },
    { value: 'balija', label: 'Balija' },
    { value: 'balija_balija_naidu', label: 'Balija-Balija Naidu' },
    { value: 'balija_balija_reddy', label: 'Balija-Balija Reddy' },
    { value: 'balija_ediga_goud_balija', label: 'Balija-Ediga /Goud (Balija)' },
    { value: 'balija_gajula_kavarai', label: 'Balija-Gajula / Kavarai' },
    { value: 'balija_kapu', label: 'Balija-Kapu' },
    { value: 'balija_kavara', label: 'Balija-Kavara' },
    { value: 'balija_linga_balija', label: 'Balija-Linga Balija' },
    { value: 'balija_modikarlu', label: 'Balija-Modikarlu' },
    { value: 'balija_munnuru_kapu', label: 'Balija-Munnuru Kapu' },
    { value: 'balija_musukama', label: 'Balija-Musukama' },
    { value: 'balija_namdarlu', label: 'Balija-Namdarlu' },
    { value: 'balija_pagadala', label: 'Balija-Pagadala' },
    { value: 'balija_perika', label: 'Balija-Perika' },
    { value: 'balija_setti_balija', label: 'Balija-Setti Balija' },
    { value: 'balija_surya_balija', label: 'Balija-Surya Balija' },
    { value: 'balija_telaga', label: 'Balija-Telaga' },
    { value: 'balija_thota', label: 'Balija-Thota' },
    { value: 'balija_vada_balija', label: 'Balija-Vada Balija' },
    { value: 'balija_velama', label: 'Balija-Velama' },
    { value: 'balija_waada_balija', label: 'Balija-Waada Balija' },
    { value: 'balija_naidu', label: 'Balija Naidu' },
    { value: 'balija_naidu_balija_naidu', label: 'Balija Naidu-Balija Naidu' },
    { value: 'balija_naidu_balija_reddy', label: 'Balija Naidu-Balija Reddy' },
    { value: 'balija_naidu_setti_balija', label: 'Balija Naidu-Setti Balija' },
    { value: 'balija_naidu_surya_balija', label: 'Balija Naidu-Surya Balija' },
    { value: 'balija_naidu_vada_balija', label: 'Balija Naidu-Vada Balija' },
    { value: 'balija_naidu_waada_balija', label: 'Balija Naidu-Waada Balija' },
    { value: 'banayat_oriya', label: 'Banayat Oriya' },
    { value: 'bania', label: 'Bania' },
    { value: 'bania_agarwal', label: 'Bania-Agarwal' },
    { value: 'bania_agrahari', label: 'Bania-Agrahari' },
    { value: 'bania_asathi', label: 'Bania-Asathi' },
    { value: 'bania_ayodhyavasi', label: 'Bania-Ayodhyavasi' },
    { value: 'bania_baniya_kumuti', label: 'Bania-Baniya Kumuti' },
    { value: 'bania_barnwals', label: 'Bania-Barnwals' },
    { value: 'bania_bisa_agarwal', label: 'Bania-Bisa Agarwal' },
    { value: 'bania_chaturth', label: 'Bania-Chaturth' },
    { value: 'bania_choudharys', label: 'Bania-Choudharys' },
    { value: 'bania_dosar_dusra', label: 'Bania-Dosar / Dusra' },
    { value: 'bania_gahoi', label: 'Bania-Gahoi' },
    { value: 'bania_gandha_vanika', label: 'Bania-Gandha Vanika' },
    { value: 'bania_gulahre', label: 'Bania-Gulahre' },
    { value: 'bania_jaiswal', label: 'Bania-Jaiswal' },
    { value: 'bania_kalwar', label: 'Bania-Kalwar' },
    { value: 'bania_kandu_kanu', label: 'Bania-Kandu / Kanu' },
    { value: 'bania_kanojia_kanu', label: 'Bania-Kanojia Kanu' },
    { value: 'bania_kanykubj_bania', label: 'Bania-Kanykubj Bania' },
    { value: 'bania_kasaundhan', label: 'Bania-Kasaundhan' },
    { value: 'bania_keshris_kesarwani', label: 'Bania-Keshris / Kesarwani' },
    { value: 'bania_khandelwal', label: 'Bania-Khandelwal' },
    { value: 'bania_komti_arya_vaishya', label: 'Bania-Komti Arya Vaishya' },
    { value: 'bania_lad', label: 'Bania-Lad' },
    { value: 'bania_madhesiya_kawa_halwai', label: 'Bania-Madhesiya / Kawa / Halwai' },
    { value: 'bania_mahajan', label: 'Bania-Mahajan' },
    { value: 'bania_mahawar', label: 'Bania-Mahawar' },
    { value: 'bania_maheshwari_meshri', label: 'Bania-Maheshwari/Meshri' },
    { value: 'bania_mahor', label: 'Bania-Mahor' },
    { value: 'bania_mahuri', label: 'Bania-Mahuri' },
    { value: 'bania_marwari', label: 'Bania-Marwari' },
    { value: 'bania_modh_ghanchi', label: 'Bania-Modh Ghanchi' },
    { value: 'bania_modi', label: 'Bania-Modi' },
    { value: 'bania_nema', label: 'Bania-Nema' },
    { value: 'bania_oswal', label: 'Bania-Oswal' },
    { value: 'bania_padmavati_porwal', label: 'Bania-Padmavati Porwal' },
    { value: 'bania_patwa', label: 'Bania-Patwa' },
    { value: 'bania_porwal_porwar', label: 'Bania-Porwal / Porwar' },
    { value: 'bania_rastogi', label: 'Bania-Rastogi' },
    { value: 'bania_rathi', label: 'Bania-Rathi' },
    { value: 'bania_rauniars', label: 'Bania-Rauniars' },
    { value: 'bania_rauniyar', label: 'Bania-Rauniyar' },
    { value: 'bania_shaw_sahu_teli', label: 'Bania-Shaw / Sahu / Teli' },
    { value: 'bania_sinduriya', label: 'Bania-Sinduriya' },
    { value: 'bania_sudi_suri_sundhi_shaundik', label: 'Bania-Sudi / Suri / Sundhi / Shaundik' },
    { value: 'bania_ummar_umre_bagaria', label: 'Bania-Ummar / Umre / Bagaria' },
    { value: 'bania_vaishnav', label: 'Bania-Vaishnav' },
    { value: 'bania_vani_vaishya', label: 'Bania-Vani/Vaishya' },
    { value: 'bania_varshneys', label: 'Bania-Varshneys' },
    { value: 'bania_vijayvargia', label: 'Bania-Vijayvargia' },
    { value: 'banik', label: 'Banik' },
    { value: 'banjara', label: 'Banjara' },
    { value: 'banjara_lambani', label: 'Banjara-Lambani' },
    { value: 'barai', label: 'Barai' },
    { value: 'bari', label: 'Bari' },
    { value: 'baria', label: 'Baria' },
    { value: 'beldar', label: 'Beldar' },
    { value: 'besta', label: 'Besta' },
    { value: 'bhajantri', label: 'Bhajantri' },
    { value: 'bhatia', label: 'Bhatia' },
    { value: 'bhatraju', label: 'Bhatraju' },
    { value: 'bhavsar', label: 'Bhavsar' },
    { value: 'bhil', label: 'Bhil' },
    { value: 'bhovi_bhoi', label: 'Bhovi / Bhoi' },
    { value: 'brahmin_all', label: 'Brahmin All' },
    { value: 'bhoyar', label: 'Bhoyar' },
    { value: 'bhulia_meher', label: 'Bhulia / Meher' },
    { value: 'billava', label: 'Billava' },
    { value: 'bishnoi_vishnoi', label: 'Bishnoi / Vishnoi' },
    { value: 'bondili', label: 'Bondili' },
    { value: 'boyer', label: 'Boyer' },
    { value: 'brahmakshatriya', label: 'Brahmakshatriya' },
    { value: 'brahmbatt', label: 'Brahmbatt' },
    { value: 'brahmin', label: 'Brahmin' },
    { value: 'brahmin_6000_niyogi', label: 'Brahmin-6000 Niyogi' },
    { value: 'brahmin_anavil', label: 'Brahmin-Anavil' },
    { value: 'brahmin_andhra', label: 'Brahmin-Andhra' },
    { value: 'brahmin_audichya', label: 'Brahmin-Audichya' },
    { value: 'brahmin_audichyasahastra', label: 'Brahmin-Audichyasahastra' },
    { value: 'brahmin_bajkhedwal', label: 'Brahmin-Bajkhedwal' },
    { value: 'brahmin_bardai', label: 'Brahmin-Bardai' },
    { value: 'brahmin_barendra', label: 'Brahmin-Barendra' },
    { value: 'brahmin_bengali', label: 'Brahmin-Bengali' },
    { value: 'jat_all', label: 'Jat All' },
    { value: 'brahmin_bhargava', label: 'Brahmin-Bhargava' },
    { value: 'brahmin_bhatt', label: 'Brahmin-Bhatt' },
    { value: 'brahmin_bhumihar', label: 'Brahmin-Bhumihar' },
    { value: 'brahmin_brahacharanam', label: 'Brahmin-Brahacharanam' },
    { value: 'brahmin_brahmbhatt', label: 'Brahmin-BrahmBhatt' },
    { value: 'brahmin_brajastha_maithil', label: 'Brahmin-Brajastha Maithil' },
    { value: 'brahmin_chittpavan_kokanastha', label: 'Brahmin-Chittpavan Kokanastha' },
    { value: 'brahmin_dadhich', label: 'Brahmin-Dadhich' },
    { value: 'brahmin_daivadnya', label: 'Brahmin-Daivadnya' },
    { value: 'brahmin_danua', label: 'Brahmin-Danua' },
    { value: 'brahmin_deshastha', label: 'Brahmin-Deshastha' },
    { value: 'brahmin_devrukhe', label: 'Brahmin-Devrukhe' },
    { value: 'brahmin_dhiman', label: 'Brahmin-Dhiman' },
    { value: 'brahmin_dravida', label: 'Brahmin-Dravida' },
    { value: 'brahmin_dunua', label: 'Brahmin-Dunua' },
    { value: 'brahmin_embrandiri', label: 'Brahmin-Embrandiri' },
    { value: 'brahmin_garhwali', label: 'Brahmin-Garhwali' },
    { value: 'brahmin_gaud_saraswat_gsb', label: 'Brahmin-Gaud Saraswat (GSB)' },
    { value: 'brahmin_gaur', label: 'Brahmin-Gaur' },
    { value: 'brahmin_gautam', label: 'Brahmin-Gautam' },
    { value: 'brahmin_goswami', label: 'Brahmin-Goswami' },
    { value: 'brahmin_gujar_gaur', label: 'Brahmin-Gujar Gaur' },
    { value: 'brahmin_gujrati', label: 'Brahmin-Gujrati' },
    { value: 'brahmin_gurukkal', label: 'Brahmin-Gurukkal' },
    { value: 'brahmin_halua', label: 'Brahmin-Halua' },
    { value: 'sindhi_all', label: 'Sindhi All' },
    { value: 'brahmin_havyaka', label: 'Brahmin-Havyaka' },
    { value: 'brahmin_hoysala', label: 'Brahmin-Hoysala' },
    { value: 'brahmin_iyengar', label: 'Brahmin-Iyengar' },
    { value: 'brahmin_iyer', label: 'Brahmin-Iyer' },
    { value: 'brahmin_jangid', label: 'Brahmin-Jangid' },
    { value: 'brahmin_jangra', label: 'Brahmin-Jangra' },
    { value: 'brahmin_jhadua', label: 'Brahmin-Jhadua' },
    { value: 'brahmin_jhijhotiya', label: 'Brahmin-Jhijhotiya' },
    { value: 'brahmin_jogi', label: 'Brahmin-Jogi' },
    { value: 'brahmin_jyotish', label: 'Brahmin-Jyotish' },
    { value: 'brahmin_kannada', label: 'Brahmin-Kannada' },
    { value: 'brahmin_kanyakubj', label: 'Brahmin-Kanyakubj' },
    { value: 'brahmin_karhade', label: 'Brahmin-Karhade' },
    { value: 'brahmin_karnataka', label: 'Brahmin-Karnataka' },
    { value: 'brahmin_kashmiri_pandit', label: 'Brahmin-Kashmiri Pandit' },
    { value: 'brahmin_khadayat', label: 'Brahmin-Khadayat' },
    { value: 'brahmin_khandelwal', label: 'Brahmin-Khandelwal' },
    { value: 'brahmin_khedaval', label: 'Brahmin-Khedaval' },
    { value: 'brahmin_koknastha', label: 'Brahmin-Koknastha' },
    { value: 'brahmin_kota', label: 'Brahmin-Kota' },
    { value: 'brahmin_kulin', label: 'Brahmin-Kulin' },
    { value: 'brahmin_kumaoni', label: 'Brahmin-Kumaoni' },
    { value: 'brahmin_madhwa', label: 'Brahmin-Madhwa' },
    { value: 'brahmin_maharastra', label: 'Brahmin-Maharastra' },
    { value: 'brahmin_maithil', label: 'Brahmin-Maithil' },
    { value: 'brahmin_malviya', label: 'Brahmin-Malviya' },
    { value: 'brahmin_marwari', label: 'Brahmin-Marwari' },
    { value: 'brahmin_mevada', label: 'Brahmin-Mevada' },
    { value: 'brahmin_modh', label: 'Brahmin-Modh' },
    { value: 'brahmin_mohapatra_mahapatra', label: 'Brahmin-Mohapatra Mahapatra' },
    { value: 'brahmin_mohyal', label: 'Brahmin-Mohyal' },
    { value: 'brahmin_nagar', label: 'Brahmin-Nagar' },
    { value: 'brahmin_namboodiri', label: 'Brahmin-Namboodiri' },
    { value: 'brahmin_narmadiya', label: 'Brahmin-Narmadiya' },
    { value: 'brahmin_nayi_nai', label: 'Brahmin-Nayi / Nai' },
    { value: 'brahmin_paliwal', label: 'Brahmin-Paliwal' },
    { value: 'brahmin_panda', label: 'Brahmin-Panda' },
    { value: 'brahmin_pandit', label: 'Brahmin-Pandit' },
    { value: 'brahmin_panicker', label: 'Brahmin-Panicker' },
    { value: 'brahmin_pareek', label: 'Brahmin-Pareek' },
    { value: 'brahmin_pushkarna', label: 'Brahmin-Pushkarna' },
    { value: 'brahmin_rajapuri_saraswat', label: 'Brahmin-Rajapuri Saraswat' },
    { value: 'brahmin_rajasthani', label: 'Brahmin-Rajasthani' },
    { value: 'brahmin_rajgor', label: 'Brahmin-Rajgor' },
    { value: 'brahmin_rarhi', label: 'Brahmin-Rarhi' },
    { value: 'brahmin_rigvedi', label: 'Brahmin-Rigvedi' },
    { value: 'brahmin_rudraj', label: 'Brahmin-Rudraj' },
    { value: 'brahmin_sachora', label: 'Brahmin-Sachora' },
    { value: 'brahmin_sakaldwipi', label: 'Brahmin-Sakaldwipi' },
    { value: 'brahmin_sanadya', label: 'Brahmin-Sanadya' },
    { value: 'brahmin_sanchihar', label: 'Brahmin-Sanchihar' },
    { value: 'brahmin_sanketi', label: 'Brahmin-Sanketi' },
    { value: 'brahmin_saraswat', label: 'Brahmin-Saraswat' },
    { value: 'brahmin_sarotri', label: 'Brahmin-Sarotri' },
    { value: 'brahmin_sarua', label: 'Brahmin-Sarua' },
    { value: 'brahmin_saryuparin', label: 'Brahmin-Saryuparin' },
    { value: 'brahmin_shivalli', label: 'Brahmin-Shivalli' },
    { value: 'brahmin_shrimali', label: 'Brahmin-Shrimali' },
    { value: 'brahmin_sikhwal', label: 'Brahmin-Sikhwal' },
    { value: 'brahmin_smartha', label: 'Brahmin-Smartha' },
    { value: 'brahmin_sri_vishnava', label: 'Brahmin-Sri Vishnava' },
    { value: 'brahmin_stanika', label: 'Brahmin-Stanika' },
    { value: 'brahmin_tapodhan', label: 'Brahmin-Tapodhan' },
    { value: 'brahmin_tyagi', label: 'Brahmin-Tyagi' },
    { value: 'brahmin_utkal', label: 'Brahmin-Utkal' },
    { value: 'brahmin_vaidiki', label: 'Brahmin-Vaidiki' },
    { value: 'brahmin_vaikhanasa', label: 'Brahmin-Vaikhanasa' },
    { value: 'brahmin_vaikhawas', label: 'Brahmin-Vaikhawas' },
    { value: 'brahmin_vaishnav', label: 'Brahmin-Vaishnav' },
    { value: 'brahmin_valam', label: 'Brahmin-Valam' },
    { value: 'brahmin_velanadu', label: 'Brahmin-Velanadu' },
    { value: 'brahmin_viswa', label: 'Brahmin-Viswa' },
    { value: 'brahmin_vyas', label: 'Brahmin-Vyas' },
    { value: 'brahmin_yajurvedi', label: 'Brahmin-Yajurvedi' },
    { value: 'brahmin_zalora', label: 'Brahmin-Zalora' },
    { value: 'brahmo', label: 'Brahmo' },
    { value: 'buddar', label: 'Buddar' },
    { value: 'bunt_shetty', label: 'Bunt Shetty' },
    { value: 'chalawadi_holeya', label: 'Chalawadi / Holeya' },
    { value: 'chamar', label: 'Chamar' },
    { value: 'chambhar', label: 'Chambhar' },
    { value: 'chandravanshi_kahar', label: 'Chandravanshi Kahar' },
    { value: 'charan', label: 'Charan' },
    { value: 'chasa', label: 'Chasa' },
    { value: 'chattada_sri_vaishnava', label: 'Chattada Sri Vaishnava' },
    { value: 'chaudary', label: 'Chaudary' },
    { value: 'chaudary_ghrit', label: 'Chaudary-Ghrit' },
    { value: 'chaurasia', label: 'Chaurasia' },
    { value: 'chennadasar', label: 'Chennadasar' },
    { value: 'cheramar', label: 'Cheramar' },
    { value: 'chettiar', label: 'Chettiar' },
    { value: 'chettiar_24_manai_telugu_chettiar', label: 'Chettiar-24 Manai Telugu Chettiar' },
    { value: 'chettiar_24_manai_telugu_chettiar_16_veedu', label: 'Chettiar-24 Manai Telugu Chettiar 16 Veedu' },
    { value: 'chettiar_24_manai_telugu_chettiar_8_veedu', label: 'Chettiar-24 Manai Telugu Chettiar 8 Veedu' },
    { value: 'chettiar_achirapakkam_chettiar', label: 'Chettiar-Achirapakkam Chettiar' },
    { value: 'chettiar_agaram_vellan_chettiar', label: 'Chettiar-Agaram Vellan Chettiar' },
    { value: 'chettiar_arya_vysya', label: 'Chettiar-Arya Vysya' },
    { value: 'chettiar_ayira_vysya', label: 'Chettiar-Ayira Vysya' },
    { value: 'chettiar_beri_chettiar', label: 'Chettiar-Beri Chettiar' },
    { value: 'chettiar_devanga_chettiar', label: 'Chettiar-Devanga Chettiar' },
    { value: 'chettiar_elur_chetty', label: 'Chettiar-Elur Chetty' },
    { value: 'chettiar_gandla_ganiga', label: 'Chettiar-Gandla / Ganiga' },
    { value: 'chettiar_kasukara', label: 'Chettiar-Kasukara' },
    { value: 'chettiar_kongu_chettiar', label: 'Chettiar-Kongu Chettiar' },
    { value: 'chettiar_kuruhini_chetty', label: 'Chettiar-Kuruhini Chetty' },
    { value: 'chettiar_manjapudur_chettiar', label: 'Chettiar-Manjapudur Chettiar' },
    { value: 'chettiar_nattukottai_chettiar', label: 'Chettiar-Nattukottai Chettiar' },
    { value: 'chettiar_padma_saliar', label: 'Chettiar-Padma Saliar' },
    { value: 'chettiar_pannirandam_chettiar', label: 'Chettiar-Pannirandam Chettiar' },
    { value: 'chettiar_parvatha_rajakulam', label: 'Chettiar-Parvatha Rajakulam' },
    { value: 'chettiar_pattinavar', label: 'Chettiar-Pattinavar' },
    { value: 'chettiar_pattusali', label: 'Chettiar-Pattusali' },
    { value: 'chettiar_sadhu_chetty', label: 'Chettiar-Sadhu Chetty' },
    { value: 'chettiar_saiva_vellan_chettiar', label: 'Chettiar-Saiva Vellan Chettiar' },
    { value: 'chettiar_senai_thalaivar', label: 'Chettiar-Senai Thalaivar' },
    { value: 'chettiar_sozhia_chettiar', label: 'Chettiar-Sozhia Chettiar' },
    { value: 'chettiar_telugupatti', label: 'Chettiar-Telugupatti' },
    { value: 'chettiar_vadambar', label: 'Chettiar-Vadambar' },
    { value: 'chettiar_vaniya_chettiar', label: 'Chettiar-Vaniya Chettiar' },
    { value: 'chettiar_vellan_chettiar', label: 'Chettiar-Vellan Chettiar' },
    { value: 'chhetri', label: 'Chhetri' },
    { value: 'chippolu_mera', label: 'Chippolu Mera' },
    { value: 'ckp', label: 'CKP' },
    { value: 'coorgi', label: 'Coorgi' },
    { value: 'coorgi_kodava', label: 'Coorgi-Kodava' },
    { value: 'dasapalanjika_kannada_saineegar', label: 'Dasapalanjika Kannada Saineegar' },
    { value: 'devadigas', label: 'Devadigas' },
    { value: 'devang_koshthi', label: 'Devang Koshthi' },
    { value: 'devang_koshthi_devanga', label: 'Devang Koshthi-Devanga' },
    { value: 'devang_koshthi_devanga_chettiar', label: 'Devang Koshthi-Devanga Chettiar' },
    { value: 'devanga', label: 'Devanga' },
    { value: 'devendra_kula_vellalar', label: 'Devendra Kula Vellalar' },
    { value: 'devipujak_vaghri', label: 'Devipujak (Vaghri)' },
    { value: 'dewar_dhibara', label: 'Dewar / Dhibara' },
    { value: 'dhanak', label: 'Dhanak' },
    { value: 'dhangar', label: 'Dhangar' },
    { value: 'dhanuk', label: 'Dhanuk' },
    { value: 'dheevara', label: 'Dheevara' },
    { value: 'dhiman', label: 'Dhiman' },
    { value: 'dhoba', label: 'Dhoba' },
    { value: 'dhobi', label: 'Dhobi' },
    { value: 'dhobi_kanaujia', label: 'Dhobi-Kanaujia' },
    { value: 'dhor_dhoar', label: 'Dhor / Dhoar' },
    { value: 'dommala', label: 'Dommala' },
    { value: 'dumal', label: 'Dumal' },
    { value: 'dusadh', label: 'Dusadh' },
    { value: 'edigas', label: 'Edigas' },
    { value: 'ezhava', label: 'Ezhava' },
    { value: 'ezhava_ezhava_panicker', label: 'Ezhava-Ezhava panicker' },
    { value: 'ezhava_ezhava_thandan', label: 'Ezhava-Ezhava Thandan' },
    { value: 'ezhava_kavuthiya', label: 'Ezhava-Kavuthiya' },
    { value: 'ezhava_thiyya', label: 'Ezhava-Thiyya' },
    { value: 'ezhuthachan', label: 'Ezhuthachan' },
    { value: 'gabit', label: 'Gabit' },
    { value: 'ganda', label: 'Ganda' },
    { value: 'gangai_ganesh', label: 'Gangai / Ganesh' },
    { value: 'ganiga', label: 'Ganiga' },
    { value: 'ganiga_shiva_jyothipana', label: 'Ganiga-Shiva Jyothipana' },
    { value: 'garhwali', label: 'Garhwali' },
    { value: 'gatti', label: 'Gatti' },
    { value: 'gavali', label: 'Gavali' },
    { value: 'gavandi', label: 'Gavandi' },
    { value: 'gavara', label: 'Gavara' },
    { value: 'ghasi', label: 'Ghasi' },
    { value: 'ghisadi', label: 'Ghisadi' },
    { value: 'ghumar', label: 'Ghumar' },
    { value: 'goala', label: 'Goala' },
    { value: 'goan', label: 'Goan' },
    { value: 'gond_gondi_raj_gond', label: 'Gond Gondi Raj Gond' },
    { value: 'gondhali', label: 'Gondhali' },
    { value: 'gopal', label: 'Gopal' },
    { value: 'goud', label: 'Goud' },
    { value: 'gounder', label: 'Gounder' },
    { value: 'gounder_kongu_vellala_gounder', label: 'Gounder-Kongu Vellala Gounder' },
    { value: 'gounder_nattu_gounder', label: 'Gounder-Nattu Gounder' },
    { value: 'gounder_urali_gounder', label: 'Gounder-Urali Gounder' },
    { value: 'gounder_vanniya_kula_kshatriyar', label: 'Gounder-Vanniya Kula Kshatriyar' },
    { value: 'gounder_vettuva_gounder', label: 'Gounder-Vettuva Gounder' },
    { value: 'gowda', label: 'Gowda' },
    { value: 'gowda_arebashe', label: 'Gowda-Arebashe' },
    { value: 'gowda_bunt', label: 'Gowda-Bunt' },
    { value: 'gowda_das', label: 'Gowda-Das' },
    { value: 'gowda_gangadikar', label: 'Gowda-Gangadikar' },
    { value: 'gowda_gowda_kuruba_gowda', label: 'Gowda-Gowda-Kuruba Gowda' },
    { value: 'gowda_hallikar', label: 'Gowda-Hallikar' },
    { value: 'gowda_hosadevaru', label: 'Gowda-Hosadevaru' },
    { value: 'gowda_kunchitaga', label: 'Gowda-Kunchitaga' },
    { value: 'gowda_morasu', label: 'Gowda-Morasu' },
    { value: 'gowda_musuku', label: 'Gowda-Musuku' },
    { value: 'gowda_namadari', label: 'Gowda-Namadari' },
    { value: 'gowda_okkaliga', label: 'Gowda-Okkaliga' },
    { value: 'gowda_reddy', label: 'Gowda-Reddy' },
    { value: 'gowda_sarpa', label: 'Gowda-Sarpa' },
    { value: 'gowda_uttamakula', label: 'Gowda-Uttamakula' },
    { value: 'gramani', label: 'Gramani' },
    { value: 'gudia', label: 'Gudia' },
    { value: 'gujjar', label: 'Gujjar' },
    { value: 'gujjar_dode', label: 'Gujjar-Dode' },
    { value: 'gujjar_leva', label: 'Gujjar-Leva' },
    { value: 'guptan', label: 'Guptan' },
    { value: 'gurav', label: 'Gurav' },
    { value: 'halba_koshti', label: 'Halba Koshti' },
    { value: 'hegde', label: 'Hegde' },
    { value: 'helava', label: 'Helava' },
    { value: 'holar', label: 'Holar' },
    { value: 'jaalari', label: 'Jaalari' },
    { value: 'jaiswal', label: 'Jaiswal' },
    { value: 'jandra', label: 'Jandra' },
    { value: 'jangam', label: 'Jangam' },
    { value: 'jat', label: 'Jat' },
    { value: 'jat_agharia', label: 'Jat-Agharia' },
    { value: 'jat_agoh', label: 'Jat-Agoh' },
    { value: 'jat_agra', label: 'Jat-Agra' },
    { value: 'jat_ahlawat', label: 'Jat-Ahlawat' },
    { value: 'jat_alwal', label: 'Jat-Alwal' },
    { value: 'jat_antil_antal', label: 'Jat-Antil / Antal' },
    { value: 'jat_arya', label: 'Jat-Arya' },
    { value: 'jat_badhwar', label: 'Jat-Badhwar' },
    { value: 'jat_bagaria', label: 'Jat-Bagaria' },
    { value: 'jat_bagri', label: 'Jat-Bagri' },
    { value: 'jat_bains', label: 'Jat-Bains' },
    { value: 'jat_balhara', label: 'Jat-Balhara' },
    { value: 'jat_balyan', label: 'Jat-Balyan' },
    { value: 'jat_bana', label: 'Jat-Bana' },
    { value: 'jat_barach', label: 'Jat-Barach' },
    { value: 'jat_bargoti', label: 'Jat-Bargoti' },
    { value: 'jat_beniwal', label: 'Jat-Beniwal' },
    { value: 'jat_bhal', label: 'Jat-Bhal' },
    { value: 'jat_bhambu', label: 'Jat-Bhambu' },
    { value: 'jat_bhodu', label: 'Jat-Bhodu' },
    { value: 'jat_bomal', label: 'Jat-Bomal' },
    { value: 'jat_budania', label: 'Jat-Budania' },
    { value: 'jat_bugaliya', label: 'Jat-Bugaliya' },
    { value: 'jat_burdak', label: 'Jat-Burdak' },
    { value: 'jat_chahal', label: 'Jat-Chahal' },
    { value: 'jat_chaudhry', label: 'Jat-Chaudhry' },
    { value: 'jat_chauhan', label: 'Jat-Chauhan' },
    { value: 'jat_chhikara_chikara', label: 'Jat-Chhikara / Chikara' },
    { value: 'jat_chillar', label: 'Jat-Chillar' },
    { value: 'jat_dabas', label: 'Jat-Dabas' },
    { value: 'jat_dagar', label: 'Jat-Dagar' },
    { value: 'jat_dagua', label: 'Jat-Dagua' },
    { value: 'jat_dahiya', label: 'Jat-Dahiya' },
    { value: 'jat_dalal', label: 'Jat-Dalal' },
    { value: 'jat_dangi', label: 'Jat-Dangi' },
    { value: 'jat_dara', label: 'Jat-Dara' },
    { value: 'jat_deshwal', label: 'Jat-Deshwal' },
    { value: 'jat_dhaka', label: 'Jat-Dhaka' },
    { value: 'jat_dhama', label: 'Jat-Dhama' },
    { value: 'jat_dhanchak', label: 'Jat-Dhanchak' },
    { value: 'jat_dhanda', label: 'Jat-Dhanda' },
    { value: 'jat_dhankhar', label: 'Jat-Dhankhar' },
    { value: 'jat_dhillon', label: 'Jat-Dhillon' },
    { value: 'jat_dhomi', label: 'Jat-Dhomi' },
    { value: 'jat_dhoot', label: 'Jat-Dhoot' },
    { value: 'jat_dhoriwal', label: 'Jat-Dhoriwal' },
    { value: 'jat_dhull', label: 'Jat-Dhull' },
    { value: 'jat_dollya', label: 'Jat-Dollya' },
    { value: 'jat_dudi', label: 'Jat-Dudi' },
    { value: 'jat_duhan', label: 'Jat-Duhan' },
    { value: 'jat_gahlot', label: 'Jat-Gahlot' },
    { value: 'jat_garhwal', label: 'Jat-Garhwal' },
    { value: 'jat_gehlawat', label: 'Jat-Gehlawat' },
    { value: 'jat_ghangas', label: 'Jat-Ghangas' },
    { value: 'jat_gill', label: 'Jat-Gill' },
    { value: 'jat_godara', label: 'Jat-Godara' },
    { value: 'jat_grewal', label: 'Jat-Grewal' },
    { value: 'jat_gulia', label: 'Jat-Gulia' },
    { value: 'jat_heer', label: 'Jat-Heer' },
    { value: 'jat_hooda', label: 'Jat-Hooda' },
    { value: 'jat_jaglon', label: 'Jat-Jaglon' },
    { value: 'jat_jakhar', label: 'Jat-Jakhar' },
    { value: 'jat_jam', label: 'Jat-Jam' },
    { value: 'jat_jaswal', label: 'Jat-Jaswal' },
    { value: 'jat_jatasra', label: 'Jat-Jatasra' },
    { value: 'jat_jewlia', label: 'Jat-Jewlia' },
    { value: 'jat_jutrana', label: 'Jat-Jutrana' },
    { value: 'jat_kadian', label: 'Jat-Kadian' },
    { value: 'jat_kahlon', label: 'Jat-Kahlon' },
    { value: 'jat_kajala', label: 'Jat-Kajala' },
    { value: 'jat_kakran', label: 'Jat-Kakran' },
    { value: 'vellalar_all', label: 'Vellalar All' },
    { value: 'jat_kalen', label: 'Jat-Kalen' },
    { value: 'jat_kaliramna', label: 'Jat-Kaliramna' },
    { value: 'jat_kalkhanse', label: 'Jat-Kalkhanse' },
    { value: 'jat_karwasra', label: 'Jat-Karwasra' },
    { value: 'jat_kaswan', label: 'Jat-Kaswan' },
    { value: 'jat_kataria', label: 'Jat-Kataria' },
    { value: 'jat_khakar', label: 'Jat-Khakar' },
    { value: 'jat_khallia', label: 'Jat-Khallia' },
    { value: 'jat_kharb', label: 'Jat-Kharb' },
    { value: 'jat_khatkar', label: 'Jat-Khatkar' },
    { value: 'jat_khatri', label: 'Jat-Khatri' },
    { value: 'jat_kherwa', label: 'Jat-Kherwa' },
    { value: 'jat_khichad', label: 'Jat-Khichad' },
    { value: 'jat_kothari', label: 'Jat-Kothari' },
    { value: 'jat_kuhar', label: 'Jat-Kuhar' },
    { value: 'jat_kulhari', label: 'Jat-Kulhari' },
    { value: 'jat_kundu', label: 'Jat-Kundu' },
    { value: 'jat_lakhlan', label: 'Jat-Lakhlan' },
    { value: 'jat_lakra', label: 'Jat-Lakra' },
    { value: 'jat_lamba', label: 'Jat-Lamba' },
    { value: 'jat_lamoria', label: 'Jat-Lamoria' },
    { value: 'jat_lather', label: 'Jat-Lather' },
    { value: 'jat_lathwal', label: 'Jat-Lathwal' },
    { value: 'jat_latiyan', label: 'Jat-Latiyan' },
    { value: 'jat_laur', label: 'Jat-Laur' },
    { value: 'jat_lehga', label: 'Jat-Lehga' },
    { value: 'jat_maan', label: 'Jat-Maan' },
    { value: 'jat_mahan', label: 'Jat-Mahan' },
    { value: 'jat_malhan', label: 'Jat-Malhan' },
    { value: 'jat_malik', label: 'Jat-Malik' },
    { value: 'jat_mandhan', label: 'Jat-Mandhan' },
    { value: 'jat_mangat', label: 'Jat-Mangat' },
    { value: 'jat_mann_rai', label: 'Jat-Mann Rai' },
    { value: 'jat_meel', label: 'Jat-Meel' },
    { value: 'jat_mehria', label: 'Jat-Mehria' },
    { value: 'jat_mhla', label: 'Jat-Mhla' },
    { value: 'jat_mohar', label: 'Jat-Mohar' },
    { value: 'jat_moond', label: 'Jat-Moond' },
    { value: 'jat_mor_more', label: 'Jat-Mor / More' },
    { value: 'jat_nain', label: 'Jat-Nain' },
    { value: 'jat_nairwal', label: 'Jat-Nairwal' },
    { value: 'jat_nandal', label: 'Jat-Nandal' },
    { value: 'jat_nara', label: 'Jat-Nara' },
    { value: 'jat_natt_nat', label: 'Jat-Natt / Nat' },
    { value: 'jat_nauhr', label: 'Jat-Nauhr' },
    { value: 'jat_nehra', label: 'Jat-Nehra' },
    { value: 'jat_nitharwal', label: 'Jat-Nitharwal' },
    { value: 'jat_ola', label: 'Jat-Ola' },
    { value: 'jat_pachehra', label: 'Jat-Pachehra' },
    { value: 'jat_palsania', label: 'Jat-Palsania' },
    { value: 'jat_panghal', label: 'Jat-Panghal' },
    { value: 'jat_panwar', label: 'Jat-Panwar' },
    { value: 'jat_parihar', label: 'Jat-Parihar' },
    { value: 'jat_pattor', label: 'Jat-Pattor' },
    { value: 'jat_pawar', label: 'Jat-Pawar' },
    { value: 'jat_phalaswal', label: 'Jat-Phalaswal' },
    { value: 'jat_phogat', label: 'Jat-Phogat' },
    { value: 'jat_pilania', label: 'Jat-Pilania' },
    { value: 'jat_pooni', label: 'Jat-Pooni' },
    { value: 'jat_punia', label: 'Jat-Punia' },
    { value: 'jat_rahan', label: 'Jat-Rahan' },
    { value: 'jat_rajaura', label: 'Jat-Rajaura' },
    { value: 'jat_rana', label: 'Jat-Rana' },
    { value: 'jat_rangi', label: 'Jat-Rangi' },
    { value: 'jat_ranwa', label: 'Jat-Ranwa' },
    { value: 'jat_rao', label: 'Jat-Rao' },
    { value: 'jat_rathi', label: 'Jat-Rathi' },
    { value: 'jat_rawal', label: 'Jat-Rawal' },
    { value: 'jat_redhu', label: 'Jat-Redhu' },
    { value: 'jat_repswal', label: 'Jat-Repswal' },
    { value: 'jat_saharan', label: 'Jat-Saharan' },
    { value: 'jat_sandhi', label: 'Jat-Sandhi' },
    { value: 'jat_sangawan', label: 'Jat-Sangawan' },
    { value: 'jat_sansanwal', label: 'Jat-Sansanwal' },
    { value: 'jat_saran', label: 'Jat-Saran' },
    { value: 'jat_saroha', label: 'Jat-Saroha' },
    { value: 'jat_sarot', label: 'Jat-Sarot' },
    { value: 'jat_sehrawat', label: 'Jat-Sehrawat' },
    { value: 'jat_sheoran', label: 'Jat-Sheoran' },
    { value: 'jat_shokeen', label: 'Jat-Shokeen' },
    { value: 'jat_sidhu', label: 'Jat-Sidhu' },
    { value: 'jat_sikarwar', label: 'Jat-Sikarwar' },
    { value: 'jat_sindhu', label: 'Jat-Sindhu' },
    { value: 'jat_singhal', label: 'Jat-Singhal' },
    { value: 'jat_sinsinwar', label: 'Jat-Sinsinwar' },
    { value: 'jat_sirohi', label: 'Jat-Sirohi' },
    { value: 'jat_siwach', label: 'Jat-Siwach' },
    { value: 'jat_solanki', label: 'Jat-Solanki' },
    { value: 'jat_suhag', label: 'Jat-Suhag' },
    { value: 'jat_sunda', label: 'Jat-Sunda' },
    { value: 'jat_takhar', label: 'Jat-Takhar' },
    { value: 'jat_tanar', label: 'Jat-Tanar' },
    { value: 'jat_tanwar', label: 'Jat-Tanwar' },
    { value: 'jat_tevatia', label: 'Jat-Tevatia' },
    { value: 'jat_thakaran', label: 'Jat-Thakaran' },
    { value: 'jat_thenua', label: 'Jat-Thenua' },
    { value: 'jat_thori', label: 'Jat-Thori' },
    { value: 'jat_tokas', label: 'Jat-Tokas' },
    { value: 'jat_tomar', label: 'Jat-Tomar' },
    { value: 'jatav', label: 'Jatav' },
    { value: 'jetty_malla', label: 'Jetty Malla' },
    { value: 'jingar', label: 'Jingar' },
    { value: 'julaha', label: 'Julaha' },
    { value: 'kachara', label: 'Kachara' },
    { value: 'kahar', label: 'Kahar' },
    { value: 'kaibarta', label: 'Kaibarta' },
    { value: 'kaikaala', label: 'Kaikaala' },
    { value: 'kayastha_all', label: 'Kayastha All' },
    { value: 'kakkalan', label: 'Kakkalan' },
    { value: 'kalal', label: 'Kalal' },
    { value: 'kalanji', label: 'Kalanji' },
    { value: 'kalar', label: 'Kalar' },
    { value: 'kalinga', label: 'Kalinga' },
    { value: 'kalinga_vysya', label: 'Kalinga Vysya' },
    { value: 'khatri_all', label: 'Khatri All' },
    { value: 'kalita', label: 'Kalita' },
    { value: 'kalwar', label: 'Kalwar' },
    { value: 'kamboj', label: 'Kamboj' },
    { value: 'kamma', label: 'Kamma' },
    { value: 'kammala', label: 'Kammala' },
    { value: 'kanakaan_padonna', label: 'Kanakaan Padonna' },
    { value: 'kanakkan_padanna', label: 'Kanakkan Padanna' },
    { value: 'kandara', label: 'Kandara' },
    { value: 'kaniyan', label: 'Kaniyan' },
    { value: 'kansari', label: 'Kansari' },
    { value: 'kansyakaar', label: 'Kansyakaar' },
    { value: 'kapol', label: 'Kapol' },
    { value: 'kapu', label: 'Kapu' },
    { value: 'kapu_balija_balija_naidu', label: 'Kapu-Balija/Balija Naidu' },
    { value: 'kapu_ediga_goud_balija', label: 'Kapu-Ediga /Goud (Balija)' },
    { value: 'kapu_gajula_kavarai', label: 'Kapu-Gajula / Kavarai' },
    { value: 'kapu_kapu_all', label: 'Kapu-Kapu All' },
    { value: 'kapu_kapu_munnuru', label: 'Kapu-Kapu Munnuru' },
    { value: 'kapu_kapu_naidu', label: 'Kapu-Kapu Naidu' },
    { value: 'kapu_kurupu_kapu', label: 'Kapu-kurupu / Kapu' },
    { value: 'kapu_ontari', label: 'Kapu-Ontari' },
    { value: 'kapu_perika', label: 'Kapu-Perika' },
    { value: 'kapu_reddy', label: 'Kapu-Reddy' },
    { value: 'kapu_setty_balija', label: 'Kapu-Setty Balija' },
    { value: 'kapu_surya_balija', label: 'Kapu-Surya Balija' },
    { value: 'kapu_telaga', label: 'Kapu-Telaga' },
    { value: 'kapu_turupu_kapu', label: 'Kapu-Turupu Kapu' },
    { value: 'kapu_velama', label: 'Kapu-Velama' },
    { value: 'kapu_munnuru', label: 'Kapu Munnuru' },
    { value: 'karakala_bhakthula', label: 'Karakala Bhakthula' },
    { value: 'karana', label: 'Karana' },
    { value: 'karmakar', label: 'Karmakar' },
    { value: 'karuneegar', label: 'Karuneegar' },
    { value: 'kasar', label: 'Kasar' },
    { value: 'kashyap', label: 'Kashyap' },
    { value: 'kashyap_nishad', label: 'Kashyap-Nishad' },
    { value: 'katiya', label: 'Katiya' },
    { value: 'kayastha', label: 'Kayastha' },
    { value: 'kayastha_ambastha', label: 'Kayastha-Ambastha' },
    { value: 'kayastha_ambastha_kayastha', label: 'Kayastha-Ambastha Kayastha' },
    { value: 'kayastha_asthana', label: 'Kayastha-Asthana' },
    { value: 'kayastha_barujibi', label: 'Kayastha-Barujibi' },
    { value: 'kayastha_basu', label: 'Kayastha-Basu' },
    { value: 'kayastha_bengali_kayastha', label: 'Kayastha-Bengali Kayastha' },
    { value: 'kayastha_bhatnagar', label: 'Kayastha-Bhatnagar' },
    { value: 'kayastha_bose', label: 'Kayastha-Bose' },
    { value: 'kayastha_chanda', label: 'Kayastha-Chanda' },
    { value: 'kayastha_dass', label: 'Kayastha-Dass' },
    { value: 'kayastha_dey', label: 'Kayastha-Dey' },
    { value: 'kayastha_dhar', label: 'Kayastha-Dhar' },
    { value: 'kayastha_dutta', label: 'Kayastha-Dutta' },
    { value: 'kayastha_ghosh', label: 'Kayastha-Ghosh' },
    { value: 'kayastha_gour', label: 'Kayastha-Gour' },
    { value: 'kayastha_guha', label: 'Kayastha-Guha' },
    { value: 'kayastha_johri', label: 'Kayastha-Johri' },
    { value: 'kayastha_karna', label: 'Kayastha-Karna' },
    { value: 'kayastha_kars', label: 'Kayastha-Kars' },
    { value: 'kayastha_kulin', label: 'Kayastha-Kulin' },
    { value: 'kayastha_kulshreshtha', label: 'Kayastha-Kulshreshtha' },
    { value: 'kayastha_mathur', label: 'Kayastha-Mathur' },
    { value: 'kayastha_mitra', label: 'Kayastha-Mitra' },
    { value: 'kayastha_nag', label: 'Kayastha-Nag' },
    { value: 'kayastha_nandi', label: 'Kayastha-Nandi' },
    { value: 'kayastha_nigam', label: 'Kayastha-Nigam' },
    { value: 'kayastha_palit', label: 'Kayastha-Palit' },
    { value: 'kayastha_paul', label: 'Kayastha-Paul' },
    { value: 'kayastha_rakshit', label: 'Kayastha-Rakshit' },
    { value: 'kayastha_rarhi', label: 'Kayastha-Rarhi' },
    { value: 'kayastha_roy', label: 'Kayastha-Roy' },
    { value: 'kayastha_saxena', label: 'Kayastha-Saxena' },
    { value: 'kayastha_sen', label: 'Kayastha-Sen' },
    { value: 'kayastha_sil', label: 'Kayastha-Sil' },
    { value: 'kayastha_sinha', label: 'Kayastha-Sinha' },
    { value: 'kayastha_srivastava', label: 'Kayastha-Srivastava' },
    { value: 'khandayat', label: 'Khandayat' },
    { value: 'khandayat_kalinja', label: 'Khandayat-Kalinja' },
    { value: 'kharvi', label: 'Kharvi' },
    { value: 'kharwar', label: 'Kharwar' },
    { value: 'khatik', label: 'Khatik' },
    { value: 'khatri', label: 'Khatri' },
    { value: 'khatri_anand', label: 'Khatri-Anand' },
    { value: 'khatri_arora', label: 'Khatri-Arora' },
    { value: 'khatri_bagga', label: 'Khatri-Bagga' },
    { value: 'khatri_bahl', label: 'Khatri-Bahl' },
    { value: 'khatri_batra', label: 'Khatri-Batra' },
    { value: 'khatri_bedi', label: 'Khatri-Bedi' },
    { value: 'khatri_behal', label: 'Khatri-Behal' },
    { value: 'khatri_behl', label: 'Khatri-Behl' },
    { value: 'khatri_beri', label: 'Khatri-Beri' },
    { value: 'khatri_bhalla', label: 'Khatri-Bhalla' },
    { value: 'khatri_bhandari', label: 'Khatri-Bhandari' },
    { value: 'khatri_bhasin', label: 'Khatri-Bhasin' },
    { value: 'khatri_bhatti', label: 'Khatri-Bhatti' },
    { value: 'khatri_chaddha', label: 'Khatri-Chaddha' },
    { value: 'khatri_chadha', label: 'Khatri-Chadha' },
    { value: 'khatri_chandok', label: 'Khatri-Chandok' },
    { value: 'khatri_chaudhary', label: 'Khatri-Chaudhary' },
    { value: 'khatri_chhabra', label: 'Khatri-Chhabra' },
    { value: 'khatri_chopra', label: 'Khatri-Chopra' },
    { value: 'khatri_choudhuri', label: 'Khatri-Choudhuri' },
    { value: 'khatri_dang', label: 'Khatri-Dang' },
    { value: 'khatri_dhawan', label: 'Khatri-Dhawan' },
    { value: 'khatri_dhir', label: 'Khatri-Dhir' },
    { value: 'khatri_duggal', label: 'Khatri-Duggal' },
    { value: 'khatri_ghai', label: 'Khatri-Ghai' },
    { value: 'khatri_handa', label: 'Khatri-Handa' },
    { value: 'khatri_jaggi', label: 'Khatri-Jaggi' },
    { value: 'khatri_jairath', label: 'Khatri-Jairath' },
    { value: 'khatri_jerath', label: 'Khatri-Jerath' },
    { value: 'khatri_jham', label: 'Khatri-Jham' },
    { value: 'khatri_kakkar', label: 'Khatri-Kakkar' },
    { value: 'khatri_kapur_kapoor', label: 'Khatri-Kapur / Kapoor' },
    { value: 'khatri_kehar', label: 'Khatri-Kehar' },
    { value: 'khatri_khanna', label: 'Khatri-Khanna' },
    { value: 'khatri_khosla', label: 'Khatri-Khosla' },
    { value: 'khatri_khukrain', label: 'Khatri-Khukrain' },
    { value: 'khatri_khullar', label: 'Khatri-Khullar' },
    { value: 'khatri_kochar', label: 'Khatri-Kochar' },
    { value: 'khatri_kohli', label: 'Khatri-Kohli' },
    { value: 'khatri_lamba', label: 'Khatri-Lamba' },
    { value: 'khatri_mahendru', label: 'Khatri-Mahendru' },
    { value: 'khatri_malhotra', label: 'Khatri-Malhotra' },
    { value: 'khatri_marwah', label: 'Khatri-Marwah' },
    { value: 'khatri_mehra', label: 'Khatri-Mehra' },
    { value: 'khatri_mehta', label: 'Khatri-Mehta' },
    { value: 'khatri_nagrath', label: 'Khatri-Nagrath' },
    { value: 'khatri_nanda', label: 'Khatri-Nanda' },
    { value: 'khatri_nayyar', label: 'Khatri-Nayyar' },
    { value: 'khatri_oberoi', label: 'Khatri-Oberoi' },
    { value: 'khatri_ohri', label: 'Khatri-Ohri' },
    { value: 'khatri_passi', label: 'Khatri-Passi' },
    { value: 'khatri_puri', label: 'Khatri-Puri' },
    { value: 'khatri_sabharwal', label: 'Khatri-Sabharwal' },
    { value: 'khatri_sahni', label: 'Khatri-Sahni' },
    { value: 'khatri_sareen', label: 'Khatri-Sareen' },
    { value: 'khatri_sarin', label: 'Khatri-Sarin' },
    { value: 'khatri_sawhney', label: 'Khatri-Sawhney' },
    { value: 'khatri_sehgal', label: 'Khatri-Sehgal' },
    { value: 'khatri_sekhri', label: 'Khatri-Sekhri' },
    { value: 'khatri_seth', label: 'Khatri-Seth' },
    { value: 'khatri_sethi', label: 'Khatri-Sethi' },
    { value: 'khatri_sobto', label: 'Khatri-Sobto' },
    { value: 'khatri_sodhi', label: 'Khatri-Sodhi' },
    { value: 'khatri_sondhi', label: 'Khatri-Sondhi' },
    { value: 'khatri_soni', label: 'Khatri-Soni' },
    { value: 'khatri_sood', label: 'Khatri-Sood' },
    { value: 'khatri_suri', label: 'Khatri-Suri' },
    { value: 'khatri_talwar', label: 'Khatri-Talwar' },
    { value: 'khatri_tandon', label: 'Khatri-Tandon' },
    { value: 'khatri_thapar', label: 'Khatri-Thapar' },
    { value: 'khatri_tuli', label: 'Khatri-Tuli' },
    { value: 'khatri_uppal', label: 'Khatri-Uppal' },
    { value: 'khatri_vadhera', label: 'Khatri-Vadhera' },
    { value: 'khatri_verma', label: 'Khatri-Verma' },
    { value: 'khatri_vij', label: 'Khatri-Vij' },
    { value: 'khatri_vohra', label: 'Khatri-Vohra' },
    { value: 'khatri_wadhawan', label: 'Khatri-Wadhawan' },
    { value: 'khatri_wahi', label: 'Khatri-Wahi' },
    { value: 'khatri_walia', label: 'Khatri-Walia' },
    { value: 'koeri_koiri', label: 'Koeri / Koiri' },
    { value: 'koli', label: 'Koli' },
    { value: 'koli_koli_mahadev', label: 'Koli-Koli Mahadev' },
    { value: 'koli_koli_patel', label: 'Koli-Koli Patel' },
    { value: 'koli_mangela', label: 'Koli-Mangela' },
    { value: 'koli_mahadev', label: 'Koli Mahadev' },
    { value: 'kondara', label: 'Kondara' },
    { value: 'kongu_vellala_gounder', label: 'Kongu Vellala Gounder' },
    { value: 'kongu_vellala_gounder_aadai', label: 'Kongu Vellala Gounder-Aadai' },
    { value: 'kongu_vellala_gounder_aadhi', label: 'Kongu Vellala Gounder-Aadhi' },
    { value: 'kongu_vellala_gounder_aanthai', label: 'Kongu Vellala Gounder-Aanthai' },
    { value: 'kongu_vellala_gounder_aavan', label: 'Kongu Vellala Gounder-Aavan' },
    { value: 'kongu_vellala_gounder_alagan', label: 'Kongu Vellala Gounder-Alagan' },
    { value: 'kongu_vellala_gounder_andai', label: 'Kongu Vellala Gounder-Andai' },
    { value: 'kongu_vellala_gounder_andhuvan', label: 'Kongu Vellala Gounder-Andhuvan' },
    { value: 'kongu_vellala_gounder_cheran', label: 'Kongu Vellala Gounder-Cheran' },
    { value: 'kongu_vellala_gounder_devendran', label: 'Kongu Vellala Gounder-Devendran' },
    { value: 'kongu_vellala_gounder_eenjan', label: 'Kongu Vellala Gounder-Eenjan' },
    { value: 'kongu_vellala_gounder_ennai', label: 'Kongu Vellala Gounder-Ennai' },
    { value: 'kongu_vellala_gounder_kaadai', label: 'Kongu Vellala Gounder-Kaadai' },
    { value: 'kongu_vellala_gounder_kaari', label: 'Kongu Vellala Gounder-Kaari' },
    { value: 'kongu_vellala_gounder_kanakkan', label: 'Kongu Vellala Gounder-Kanakkan' },
    { value: 'kongu_vellala_gounder_kannan', label: 'Kongu Vellala Gounder-Kannan' },
    { value: 'kongu_vellala_gounder_kannandhai', label: 'Kongu Vellala Gounder-Kannandhai' },
    { value: 'kongu_vellala_gounder_keeran', label: 'Kongu Vellala Gounder-Keeran' },
    { value: 'kongu_vellala_gounder_koorai', label: 'Kongu Vellala Gounder-Koorai' },
    { value: 'kongu_vellala_gounder_koventhar', label: 'Kongu Vellala Gounder-Koventhar' },
    { value: 'kongu_vellala_gounder_kuzhlaayan', label: 'Kongu Vellala Gounder-Kuzhlaayan' },
    { value: 'kongu_vellala_gounder_maadai', label: 'Kongu Vellala Gounder-Maadai' },
    { value: 'kongu_vellala_gounder_maniyan', label: 'Kongu Vellala Gounder-Maniyan' },
    { value: 'kongu_vellala_gounder_medhi', label: 'Kongu Vellala Gounder-Medhi' },
    { value: 'kongu_vellala_gounder_muthan', label: 'Kongu Vellala Gounder-Muthan' },
    { value: 'kongu_vellala_gounder_muzhlukkadhan', label: 'Kongu Vellala Gounder-Muzhlukkadhan' },
    { value: 'kongu_vellala_gounder_nattu_gounder', label: 'Kongu Vellala Gounder-Nattu Gounder' },
    { value: 'kongu_vellala_gounder_odhaalar', label: 'Kongu Vellala Gounder-Odhaalar' },
    { value: 'kongu_vellala_gounder_paandian', label: 'Kongu Vellala Gounder-Paandian' },
    { value: 'kongu_vellala_gounder_padaithalaiyan', label: 'Kongu Vellala Gounder-Padaithalaiyan' },
    { value: 'kongu_vellala_gounder_panaiyan', label: 'Kongu Vellala Gounder-Panaiyan' },
    { value: 'kongu_vellala_gounder_panangadai', label: 'Kongu Vellala Gounder-Panangadai' },
    { value: 'kongu_vellala_gounder_pannai', label: 'Kongu Vellala Gounder-Pannai' },
    { value: 'kongu_vellala_gounder_pannan', label: 'Kongu Vellala Gounder-Pannan' },
    { value: 'kongu_vellala_gounder_pavalan', label: 'Kongu Vellala Gounder-Pavalan' },
    { value: 'kongu_vellala_gounder_payiran', label: 'Kongu Vellala Gounder-Payiran' },
    { value: 'kongu_vellala_gounder_periyan', label: 'Kongu Vellala Gounder-Periyan' },
    { value: 'kongu_vellala_gounder_perizhanthan', label: 'Kongu Vellala Gounder-Perizhanthan' },
    { value: 'kongu_vellala_gounder_perunkudi', label: 'Kongu Vellala Gounder-Perunkudi' },
    { value: 'kongu_vellala_gounder_pillan', label: 'Kongu Vellala Gounder-Pillan' },
    { value: 'kongu_vellala_gounder_podiyan', label: 'Kongu Vellala Gounder-Podiyan' },
    { value: 'kongu_vellala_gounder_ponnan', label: 'Kongu Vellala Gounder-Ponnan' },
    { value: 'kongu_vellala_gounder_poochadhai_poodhiyan', label: 'Kongu Vellala Gounder-Poochadhai Poodhiyan' },
    { value: 'kongu_vellala_gounder_poosan', label: 'Kongu Vellala Gounder-Poosan' },
    { value: 'kongu_vellala_gounder_sathandhai', label: 'Kongu Vellala Gounder-Sathandhai' },
    { value: 'kongu_vellala_gounder_sedan', label: 'Kongu Vellala Gounder-Sedan' },
    { value: 'kongu_vellala_gounder_sellan', label: 'Kongu Vellala Gounder-Sellan' },
    { value: 'kongu_vellala_gounder_sempoothan', label: 'Kongu Vellala Gounder-Sempoothan' },
    { value: 'kongu_vellala_gounder_sengannan', label: 'Kongu Vellala Gounder-Sengannan' },
    { value: 'kongu_vellala_gounder_sengunni', label: 'Kongu Vellala Gounder-Sengunni' },
    { value: 'kongu_vellala_gounder_seralan', label: 'Kongu Vellala Gounder-Seralan' },
    { value: 'kongu_vellala_gounder_sevadi', label: 'Kongu Vellala Gounder-Sevadi' },
    { value: 'kongu_vellala_gounder_thodai', label: 'Kongu Vellala Gounder-Thodai' },
    { value: 'kongu_vellala_gounder_thooran', label: 'Kongu Vellala Gounder-Thooran' },
    { value: 'kongu_vellala_gounder_vannakkan', label: 'Kongu Vellala Gounder-Vannakkan' },
    { value: 'kongu_vellala_gounder_veliyan', label: 'Kongu Vellala Gounder-Veliyan' },
    { value: 'kongu_vellala_gounder_vellamban', label: 'Kongu Vellala Gounder-Vellamban' },
    { value: 'kongu_vellala_gounder_venduvan', label: 'Kongu Vellala Gounder-Venduvan' },
    { value: 'kongu_vellala_gounder_viliyan', label: 'Kongu Vellala Gounder-Viliyan' },
    { value: 'kongu_vellala_gounder_villi', label: 'Kongu Vellala Gounder-Villi' },
    { value: 'konkani', label: 'Konkani' },
    { value: 'koracha', label: 'Koracha' },
    { value: 'korama', label: 'Korama' },
    { value: 'kori', label: 'Kori' },
    { value: 'kori_koli', label: 'Kori / Koli' },
    { value: 'korvi', label: 'Korvi' },
    { value: 'koshti', label: 'Koshti' },
    { value: 'krishnavaka', label: 'Krishnavaka' },
    { value: 'kshatriya', label: 'Kshatriya' },
    { value: 'kshatriya_agnikula_kshatriya', label: 'Kshatriya-Agnikula Kshatriya' },
    { value: 'kshatriya_aguri_ugra_kshatriya', label: 'Kshatriya-Aguri Ugra Kshatriya' },
    { value: 'kshatriya_amethia', label: 'Kshatriya-Amethia' },
    { value: 'kshatriya_bachhil', label: 'Kshatriya-Bachhil' },
    { value: 'kshatriya_bagel', label: 'Kshatriya-Bagel' },
    { value: 'kshatriya_baghela_veghela', label: 'Kshatriya-Baghela / Veghela' },
    { value: 'kshatriya_banafar', label: 'Kshatriya-Banafar' },
    { value: 'kshatriya_bhadoria', label: 'Kshatriya-Bhadoria' },
    { value: 'kshatriya_bhandari', label: 'Kshatriya-Bhandari' },
    { value: 'kshatriya_bhardwaj', label: 'Kshatriya-Bhardwaj' },
    { value: 'kshatriya_bhatraju', label: 'Kshatriya-Bhatraju' },
    { value: 'kshatriya_bhavasar_kshatriya', label: 'Kshatriya-Bhavasar Kshatriya' },
    { value: 'kshatriya_bundela', label: 'Kshatriya-Bundela' },
    { value: 'kshatriya_chopra', label: 'Kshatriya-Chopra' },
    { value: 'kshatriya_chudasa', label: 'Kshatriya-Chudasa' },
    { value: 'kshatriya_dangi', label: 'Kshatriya-Dangi' },
    { value: 'kshatriya_dhawan', label: 'Kshatriya-Dhawan' },
    { value: 'kshatriya_dixit', label: 'Kshatriya-Dixit' },
    { value: 'kshatriya_gaherwar', label: 'Kshatriya-Gaherwar' },
    { value: 'kshatriya_gargvansi', label: 'Kshatriya-Gargvansi' },
    { value: 'kshatriya_gaur', label: 'Kshatriya-Gaur' },
    { value: 'kshatriya_hada', label: 'Kshatriya-Hada' },
    { value: 'kshatriya_haihaivanshi', label: 'Kshatriya-Haihaivanshi' },
    { value: 'kshatriya_jaiswar', label: 'Kshatriya-Jaiswar' },
    { value: 'kshatriya_janwar', label: 'Kshatriya-Janwar' },
    { value: 'kshatriya_kandera', label: 'Kshatriya-Kandera' },
    { value: 'kshatriya_kapur', label: 'Kshatriya-Kapur' },
    { value: 'kshatriya_katiyar', label: 'Kshatriya-Katiyar' },
    { value: 'kshatriya_khandayat', label: 'Kshatriya-Khandayat' },
    { value: 'kshatriya_khanna', label: 'Kshatriya-Khanna' },
    { value: 'kshatriya_khare', label: 'Kshatriya-Khare' },
    { value: 'kshatriya_kshatriya_raju', label: 'Kshatriya-Kshatriya Raju' },
    { value: 'kshatriya_kshatriya_raju_chandravamsam', label: 'Kshatriya-Kshatriya Raju Chandravamsam' },
    { value: 'kshatriya_kshatriya_raju_suryavamsam', label: 'Kshatriya-Kshatriya Raju Suryavamsam' },
    { value: 'kshatriya_kumawat', label: 'Kshatriya-Kumawat' },
    { value: 'kshatriya_kurmi', label: 'Kshatriya-Kurmi' },
    { value: 'kshatriya_mehra', label: 'Kshatriya-Mehra' },
    { value: 'kshatriya_nagvanshi', label: 'Kshatriya-Nagvanshi' },
    { value: 'kshatriya_negi', label: 'Kshatriya-Negi' },
    { value: 'kshatriya_niari', label: 'Kshatriya-Niari' },
    { value: 'kshatriya_nikhumbh', label: 'Kshatriya-Nikhumbh' },
    { value: 'kshatriya_paliwal', label: 'Kshatriya-Paliwal' },
    { value: 'kshatriya_pawar', label: 'Kshatriya-Pawar' },
    { value: 'kshatriya_perika_puragiri_kshatriya', label: 'Kshatriya-Perika Puragiri Kshatriya' },
    { value: 'kshatriya_pundir', label: 'Kshatriya-Pundir' },
    { value: 'kshatriya_raikwar', label: 'Kshatriya-Raikwar' },
    { value: 'kshatriya_rajkumar', label: 'Kshatriya-Rajkumar' },
    { value: 'kshatriya_rajwar', label: 'Kshatriya-Rajwar' },
    { value: 'kshatriya_rama_kshatriya', label: 'Kshatriya-Rama Kshatriya' },
    { value: 'kshatriya_rathor', label: 'Kshatriya-Rathor' },
    { value: 'kshatriya_rawal', label: 'Kshatriya-Rawal' },
    { value: 'kshatriya_rawat', label: 'Kshatriya-Rawat' },
    { value: 'kshatriya_sahni', label: 'Kshatriya-Sahni' },
    { value: 'kshatriya_saithwar_mall', label: 'Kshatriya-Saithwar- Mall' },
    { value: 'kshatriya_sami', label: 'Kshatriya-Sami' },
    { value: 'kshatriya_sengar', label: 'Kshatriya-Sengar' },
    { value: 'kshatriya_seth', label: 'Kshatriya-Seth' },
    { value: 'kshatriya_shrinet', label: 'Kshatriya-Shrinet' },
    { value: 'kshatriya_singh', label: 'Kshatriya-Singh' },
    { value: 'kshatriya_sisodiya', label: 'Kshatriya-Sisodiya' },
    { value: 'kshatriya_soma_vamsha_arya_kshatriya', label: 'Kshatriya-Soma Vamsha Arya Kshatriya' },
    { value: 'kshatriya_somavanshi_sahasrarjun_kshatriya', label: 'Kshatriya-Somavanshi Sahasrarjun Kshatriya' },
    { value: 'kshatriya_somvanshi', label: 'Kshatriya-Somvanshi' },
    { value: 'kshatriya_tandon', label: 'Kshatriya-Tandon' },
    { value: 'kshatriya_tanwar', label: 'Kshatriya-Tanwar' },
    { value: 'kshatriya_thogata_veera_kshatriya', label: 'Kshatriya-Thogata Veera Kshatriya' },
    { value: 'kshatriya_tomar_tanwar', label: 'Kshatriya-Tomar / Tanwar' },
    { value: 'kshatriya_tong_kshatriya', label: 'Kshatriya-Tong Kshatriya' },
    { value: 'kshatriya_vahi', label: 'Kshatriya-Vahi' },
    { value: 'kshatriya_vohra', label: 'Kshatriya-Vohra' },
    { value: 'kshatriya_wadhwa', label: 'Kshatriya-Wadhwa' },
    { value: 'kshatriya_agnikula', label: 'Kshatriya Agnikula' },
    { value: 'kudumbi', label: 'Kudumbi' },
    { value: 'kulalar', label: 'Kulalar' },
    { value: 'kulita', label: 'Kulita' },
    { value: 'kumaoni', label: 'Kumaoni' },
    { value: 'kumawat', label: 'Kumawat' },
    { value: 'kumbhakar', label: 'Kumbhakar' },
    { value: 'kumhar_kumbhar', label: 'Kumhar / Kumbhar' },
    { value: 'kummari', label: 'Kummari' },
    { value: 'kunbi', label: 'Kunbi' },
    { value: 'rajput_all', label: 'Rajput All' },
    { value: 'kunbi_ghatode', label: 'Kunbi-Ghatode' },
    { value: 'kunbi_kunbi_dhanoje', label: 'Kunbi-Kunbi- Dhanoje' },
    { value: 'kunbi_kunbi_khaire', label: 'Kunbi-Kunbi- Khaire' },
    { value: 'kunbi_kunbi_khedule', label: 'Kunbi-Kunbi- Khedule' },
    { value: 'kunbi_kunbi_lonari', label: 'Kunbi-Kunbi- Lonari' },
    { value: 'kunbi_kunbi_maratha', label: 'Kunbi-Kunbi- Maratha' },
    { value: 'kunbi_kunbi_tirale', label: 'Kunbi-Kunbi- Tirale' },
    { value: 'kunbi_zade', label: 'Kunbi-Zade' },
    { value: 'kurava', label: 'Kurava' },
    { value: 'maratha_all', label: 'Maratha All' },
    { value: 'kuravan_kuravar', label: 'Kuravan / Kuravar' },
    { value: 'kurmi', label: 'Kurmi' },
    { value: 'kurmi_awadhiya', label: 'Kurmi-Awadhiya' },
    { value: 'kurmi_baghel', label: 'Kurmi-Baghel' },
    { value: 'kurmi_chandel', label: 'Kurmi-Chandel' },
    { value: 'kurmi_chandra', label: 'Kurmi-Chandra' },
    { value: 'kurmi_chandrakar', label: 'Kurmi-Chandrakar' },
    { value: 'kurmi_chandrawanshi', label: 'Kurmi-Chandrawanshi' },
    { value: 'kurmi_chaudhary', label: 'Kurmi-Chaudhary' },
    { value: 'kurmi_chaudhury', label: 'Kurmi-Chaudhury' },
    { value: 'kurmi_deshmukh', label: 'Kurmi-Deshmukh' },
    { value: 'kurmi_gangwar', label: 'Kurmi-Gangwar' },
    { value: 'kurmi_ghamaila', label: 'Kurmi-Ghamaila' },
    { value: 'kurmi_jaiswar', label: 'Kurmi-Jaiswar' },
    { value: 'kurmi_kashyap', label: 'Kurmi-Kashyap' },
    { value: 'kurmi_katiyar', label: 'Kurmi-Katiyar' },
    { value: 'kurmi_kochyasa', label: 'Kurmi-Kochyasa' },
    { value: 'kurmi_kumar', label: 'Kurmi-Kumar' },
    { value: 'kurmi_kushwaha_koiri', label: 'Kurmi-Kushwaha (Koiri)' },
    { value: 'kurmi_mahata', label: 'Kurmi-Mahata' },
    { value: 'kurmi_mahato', label: 'Kurmi-Mahato' },
    { value: 'kurmi_mahto', label: 'Kurmi-Mahto' },
    { value: 'kurmi_parganiha', label: 'Kurmi-Parganiha' },
    { value: 'kurmi_patel', label: 'Kurmi-Patel' },
    { value: 'kurmi_patidar', label: 'Kurmi-Patidar' },
    { value: 'kurmi_prasad', label: 'Kurmi-Prasad' },
    { value: 'kurmi_rai', label: 'Kurmi-Rai' },
    { value: 'kurmi_sachan', label: 'Kurmi-Sachan' },
    { value: 'kurmi_singh', label: 'Kurmi-Singh' },
    { value: 'kurmi_verma', label: 'Kurmi-Verma' },
    { value: 'kurmi_kshatriya', label: 'Kurmi Kshatriya' },
    { value: 'kurmi_kshatriya_awadhya', label: 'Kurmi Kshatriya-Awadhya' },
    { value: 'kurmi_kshatriya_baghel', label: 'Kurmi Kshatriya-Baghel' },
    { value: 'kurmi_kshatriya_chandel', label: 'Kurmi Kshatriya-Chandel' },
    { value: 'kurmi_kshatriya_chandra', label: 'Kurmi Kshatriya-Chandra' },
    { value: 'kurmi_kshatriya_chandrakar', label: 'Kurmi Kshatriya-Chandrakar' },
    { value: 'kurmi_kshatriya_chandrawanshi', label: 'Kurmi Kshatriya-Chandrawanshi' },
    { value: 'kurmi_kshatriya_chaudhury', label: 'Kurmi Kshatriya-Chaudhury' },
    { value: 'kurmi_kshatriya_deshmukh', label: 'Kurmi Kshatriya-Deshmukh' },
    { value: 'kurmi_kshatriya_gangwar', label: 'Kurmi Kshatriya-Gangwar' },
    { value: 'kurmi_kshatriya_ghamaila', label: 'Kurmi Kshatriya-Ghamaila' },
    { value: 'kurmi_kshatriya_jaiswar', label: 'Kurmi Kshatriya-Jaiswar' },
    { value: 'kurmi_kshatriya_kashyap', label: 'Kurmi Kshatriya-Kashyap' },
    { value: 'kurmi_kshatriya_katiyar', label: 'Kurmi Kshatriya-Katiyar' },
    { value: 'kurmi_kshatriya_kochaisa', label: 'Kurmi Kshatriya-Kochaisa' },
    { value: 'kurmi_kshatriya_kumar', label: 'Kurmi Kshatriya-Kumar' },
    { value: 'kurmi_kshatriya_kushwaha_koiri', label: 'Kurmi Kshatriya-Kushwaha Koiri' },
    { value: 'kurmi_kshatriya_mahata', label: 'Kurmi Kshatriya-Mahata' },
    { value: 'kurmi_kshatriya_mahato', label: 'Kurmi Kshatriya-Mahato' },
    { value: 'kurmi_kshatriya_mahto', label: 'Kurmi Kshatriya-Mahto' },
    { value: 'kurmi_kshatriya_parganiha', label: 'Kurmi Kshatriya-Parganiha' },
    { value: 'kurmi_kshatriya_patel', label: 'Kurmi Kshatriya-Patel' },
    { value: 'kurmi_kshatriya_prasad', label: 'Kurmi Kshatriya-Prasad' },
    { value: 'kurmi_kshatriya_rai', label: 'Kurmi Kshatriya-Rai' },
    { value: 'kurmi_kshatriya_sachan', label: 'Kurmi Kshatriya-Sachan' },
    { value: 'kurmi_kshatriya_singh', label: 'Kurmi Kshatriya-Singh' },
    { value: 'kurmi_kshatriya_verma', label: 'Kurmi Kshatriya-Verma' },
    { value: 'kuruba', label: 'Kuruba' },
    { value: 'kuruhina_shetty', label: 'Kuruhina Shetty' },
    { value: 'kurumbar', label: 'Kurumbar' },
    { value: 'kuruva', label: 'Kuruva' },
    { value: 'kushwaha', label: 'Kushwaha' },
    { value: 'kutchi', label: 'Kutchi' },
    { value: 'kutchi_gurjar', label: 'Kutchi Gurjar' },
    { value: 'lambadi', label: 'Lambadi' },
    { value: 'laxminarayan_gola', label: 'Laxminarayan gola' },
    { value: 'leva_patidar', label: 'Leva Patidar' },
    { value: 'leva_patil', label: 'Leva Patil' },
    { value: 'lingayat', label: 'Lingayat' },
    { value: 'lingayat_agasa', label: 'Lingayat-Agasa' },
    { value: 'lingayat_akkasali', label: 'Lingayat-Akkasali' },
    { value: 'lingayat_aradhya', label: 'Lingayat-Aradhya' },
    { value: 'lingayat_balegala', label: 'Lingayat-Balegala' },
    { value: 'lingayat_banagar', label: 'Lingayat-Banagar' },
    { value: 'lingayat_banajiga', label: 'Lingayat-Banajiga' },
    { value: 'lingayat_bhandari', label: 'Lingayat-Bhandari' },
    { value: 'lingayat_bilijedaru', label: 'Lingayat-Bilijedaru' },
    { value: 'lingayat_bilimagga', label: 'Lingayat-Bilimagga' },
    { value: 'lingayat_chaturtha', label: 'Lingayat-Chaturtha' },
    { value: 'lingayat_dikshwant', label: 'Lingayat-Dikshwant' },
    { value: 'lingayat_ganiga', label: 'Lingayat-Ganiga' },
    { value: 'lingayat_gowda', label: 'Lingayat-Gowda' },
    { value: 'lingayat_gowli', label: 'Lingayat-Gowli' },
    { value: 'scheduled_caste_all', label: 'Scheduled Caste All' },
    { value: 'lingayat_gurav', label: 'Lingayat-Gurav' },
    { value: 'lingayat_hadapada', label: 'Lingayat-Hadapada' },
    { value: 'lingayat_hatgar', label: 'Lingayat-Hatgar' },
    { value: 'lingayat_hoogar_hugar_jeer', label: 'Lingayat-Hoogar / Hugar / Jeer' },
    { value: 'lingayat_jadaru', label: 'Lingayat-Jadaru' },
    { value: 'lingayat_jangam', label: 'Lingayat-Jangam' },
    { value: 'lingayat_kudu_vokkaliga', label: 'Lingayat-Kudu Vokkaliga' },
    { value: 'lingayat_kumbar_kumbara', label: 'Lingayat-Kumbar / Kumbara' },
    { value: 'lingayat_kumbhar', label: 'Lingayat-Kumbhar' },
    { value: 'lingayat_kuruhina_setty', label: 'Lingayat-Kuruhina Setty' },
    { value: 'lingayat_lamba', label: 'Lingayat-lamba' },
    { value: 'lingayat_lolagonda', label: 'Lingayat-Lolagonda' },
    { value: 'lingayat_madivala', label: 'Lingayat-Madivala' },
    { value: 'lingayat_malgar', label: 'Lingayat-Malgar' },
    { value: 'lingayat_mali', label: 'Lingayat-Mali' },
    { value: 'lingayat_neelagar', label: 'Lingayat-Neelagar' },
    { value: 'lingayat_neeli_neelagar', label: 'Lingayat-Neeli / Neelagar' },
    { value: 'lingayat_neygi', label: 'Lingayat-Neygi' },
    { value: 'lingayat_nolamba', label: 'Lingayat-Nolamba' },
    { value: 'lingayat_pancham', label: 'Lingayat-Pancham' },
    { value: 'lingayat_panchamasali', label: 'Lingayat-Panchamasali' },
    { value: 'lingayat_pattasali', label: 'Lingayat-Pattasali' },
    { value: 'lingayat_reddy_reddi', label: 'Lingayat-Reddy Reddi' },
    { value: 'lingayat_sadar', label: 'Lingayat-Sadar' },
    { value: 'lingayat_sajjan_sajjanaganigar', label: 'Lingayat-Sajjan / Sajjanaganigar' },
    { value: 'lingayat_setty', label: 'Lingayat-Setty' },
    { value: 'lingayat_shilwant', label: 'Lingayat-Shilwant' },
    { value: 'lingayat_shiva_simpi', label: 'Lingayat-Shiva Simpi' },
    { value: 'lingayat_vani', label: 'Lingayat-Vani' },
    { value: 'lingayat_veerashaiva', label: 'Lingayat-Veerashaiva' },
    { value: 'lohana', label: 'Lohana' },
    { value: 'lohana_ghoghari', label: 'Lohana-Ghoghari' },
    { value: 'lohana_halai', label: 'Lohana-Halai' },
    { value: 'lohana_kutchi', label: 'Lohana-Kutchi' },
    { value: 'lohana_vaishnav', label: 'Lohana-Vaishnav' },
    { value: 'lohar', label: 'Lohar' },
    { value: 'lubana', label: 'Lubana' },
    { value: 'madiga', label: 'Madiga' },
    { value: 'mahar', label: 'Mahar' },
    { value: 'mahendra', label: 'Mahendra' },
    { value: 'maheshwari', label: 'Maheshwari' },
    { value: 'mahindra', label: 'Mahindra' },
    { value: 'mahisya', label: 'Mahisya' },
    { value: 'majabi_mazhbi', label: 'Majabi Mazhbi' },
    { value: 'mala', label: 'Mala' },
    { value: 'mali', label: 'Mali' },
    { value: 'mallah', label: 'Mallah' },
    { value: 'mallah_kewat_keot', label: 'Mallah-Kewat / Keot' },
    { value: 'mallah_nishad', label: 'Mallah-Nishad' },
    { value: 'manikpuri', label: 'Manikpuri' },
    { value: 'manipuri', label: 'Manipuri' },
    { value: 'manjhi', label: 'Manjhi' },
    { value: 'mannan_velon_vannan', label: 'Mannan / Velon / Vannan' },
    { value: 'mapila', label: 'Mapila' },
    { value: 'maratha', label: 'Maratha' },
    { value: 'maratha_96_kuli_maratha', label: 'Maratha-96 Kuli Maratha' },
    { value: 'maratha_96k_kokanastha', label: 'Maratha-96K Kokanastha' },
    { value: 'maratha_aramari_gabit', label: 'Maratha-Aramari Gabit' },
    { value: 'maratha_deshastha_maratha', label: 'Maratha-Deshastha Maratha' },
    { value: 'maratha_deshmukh', label: 'Maratha-Deshmukh' },
    { value: 'maratha_deshtha_maratha', label: 'Maratha-Deshtha Maratha' },
    { value: 'maratha_gomantak_maratha', label: 'Maratha-Gomantak Maratha' },
    { value: 'maratha_jhadav', label: 'Maratha-Jhadav' },
    { value: 'maratha_kokanastha_maratha', label: 'Maratha-Kokanastha Maratha' },
    { value: 'maratha_kunbi_dhanoje', label: 'Maratha-Kunbi Dhanoje' },
    { value: 'maratha_kunbi_khaire', label: 'Maratha-Kunbi Khaire' },
    { value: 'maratha_kunbi_khedule', label: 'Maratha-Kunbi Khedule' },
    { value: 'maratha_kunbi_lonari', label: 'Maratha-Kunbi Lonari' },
    { value: 'maratha_kunbi_maratha', label: 'Maratha-Kunbi Maratha' },
    { value: 'maratha_kunbi_tirale', label: 'Maratha-Kunbi Tirale' },
    { value: 'maratha_malwani', label: 'Maratha-Malwani' },
    { value: 'maratha_maratha_kshatriya', label: 'Maratha-Maratha Kshatriya' },
    { value: 'maratha_parit', label: 'Maratha-Parit' },
    { value: 'maratha_patil', label: 'Maratha-Patil' },
    { value: 'maratha_sonar', label: 'Maratha-Sonar' },
    { value: 'maratha_suthar', label: 'Maratha-Suthar' },
    { value: 'maratha_vani', label: 'Maratha-Vani' },
    { value: 'maravar', label: 'Maravar' },
    { value: 'maruthuvar', label: 'Maruthuvar' },
    { value: 'matang', label: 'Matang' },
    { value: 'maurya', label: 'Maurya' },
    { value: 'maurya_kachchi', label: 'Maurya-Kachchi' },
    { value: 'maurya_kushwaha', label: 'Maurya-Kushwaha' },
    { value: 'meda', label: 'Meda' },
    { value: 'meena', label: 'Meena' },
    { value: 'meenavar', label: 'Meenavar' },
    { value: 'meghwal', label: 'Meghwal' },
    { value: 'mehra', label: 'Mehra' },
    { value: 'mehtar', label: 'Mehtar' },
    { value: 'menon', label: 'Menon' },
    { value: 'meru', label: 'Meru' },
    { value: 'meru_darji', label: 'Meru darji' },
    { value: 'mochi', label: 'Mochi' },
    { value: 'modak', label: 'Modak' },
    { value: 'mogaveera', label: 'Mogaveera' },
    { value: 'monchi', label: 'Monchi' },
    { value: 'patel_all', label: 'Patel All' },
    { value: 'motati_reddy', label: 'Motati Reddy' },
    { value: 'mudaliar', label: 'Mudaliar' },
    { value: 'mudaliar_agamudayar_arcot_thuluva_vellala', label: 'Mudaliar-Agamudayar/Arcot/Thuluva Vellala' },
    { value: 'mudaliar_isai_vellalar', label: 'Mudaliar-Isai Vellalar' },
    { value: 'mudaliar_kerala_mudali', label: 'Mudaliar-Kerala Mudali' },
    { value: 'mudaliar_kongu_vellala_gounder', label: 'Mudaliar-Kongu Vellala Gounder' },
    { value: 'mudaliar_mudailiar_arcot', label: 'Mudaliar-Mudailiar Arcot' },
    { value: 'mudaliar_mudaliar_all', label: 'Mudaliar-Mudaliar All' },
    { value: 'mudaliar_mudaliar_saiva', label: 'Mudaliar-Mudaliar Saiva' },
    { value: 'mudaliar_mudaliar_sengupta', label: 'Mudaliar-Mudaliar Sengupta' },
    { value: 'mudaliar_saiva_pillai_tirunelveli', label: 'Mudaliar-Saiva Pillai Tirunelveli' },
    { value: 'mudaliar_sengunthar_kaikolar', label: 'Mudaliar-Sengunthar/Kaikolar' },
    { value: 'mudaliar_sozhiya_vellalar', label: 'Mudaliar-Sozhiya Vellalar' },
    { value: 'mudaliar_thondai_mandala_vellala', label: 'Mudaliar-Thondai Mandala Vellala' },
    { value: 'mudaliar_veerakodi_vellala', label: 'Mudaliar-Veerakodi Vellala' },
    { value: 'mudaliar_arcot', label: 'Mudaliar Arcot' },
    { value: 'mudiraj', label: 'Mudiraj' },
    { value: 'muthuraja', label: 'Muthuraja' },
    { value: 'naagavamsam', label: 'Naagavamsam' },
    { value: 'nadar', label: 'Nadar' },
    { value: 'nadar_kongu_nadar', label: 'Nadar-Kongu Nadar' },
    { value: 'nagaralu', label: 'Nagaralu' },
    { value: 'naicker', label: 'Naicker' },
    { value: 'naicker_naicker_others', label: 'Naicker-Naicker others' },
    { value: 'naicker_naicker_vanniya_kula_kshatriyar', label: 'Naicker-Naicker-Vanniya Kula Kshatriyar' },
    { value: 'naicker_rajaka_chakali_dhobi', label: 'Naicker-Rajaka Chakali Dhobi' },
    { value: 'naidu', label: 'Naidu' },
    { value: 'naidu_balija_naidu', label: 'Naidu-Balija Naidu' },
    { value: 'naidu_ediga_goud', label: 'Naidu-Ediga /Goud' },
    { value: 'naidu_gajula_kavarai', label: 'Naidu-Gajula Kavarai' },
    { value: 'naidu_gavara', label: 'Naidu-Gavara' },
    { value: 'naidu_kamma', label: 'Naidu-Kamma' },
    { value: 'naidu_kapu_naidu', label: 'Naidu-Kapu Naidu' },
    { value: 'naidu_munnuru_kapu', label: 'Naidu-Munnuru Kapu' },
    { value: 'naidu_mutharaja', label: 'Naidu-Mutharaja' },
    { value: 'naidu_perika', label: 'Naidu-Perika' },
    { value: 'naidu_raja_kambalathu_naicker', label: 'Naidu-Raja Kambalathu Naicker' },
    { value: 'naidu_raju', label: 'Naidu-Raju' },
    { value: 'naidu_reddy', label: 'Naidu-Reddy' },
    { value: 'naidu_shetty_balija', label: 'Naidu-Shetty Balija' },
    { value: 'naidu_surya_balija', label: 'Naidu-Surya Balija' },
    { value: 'naidu_telaga', label: 'Naidu-Telaga' },
    { value: 'naidu_turupu_kapu', label: 'Naidu-Turupu Kapu' },
    { value: 'naidu_vada_balija', label: 'Naidu-Vada Balija' },
    { value: 'naidu_vadugan', label: 'Naidu-Vadugan' },
    { value: 'naidu_velama', label: 'Naidu-Velama' },
    { value: 'naidu_yadava_naidu', label: 'Naidu-Yadava Naidu' },
    { value: 'naik_nayak_nayaka', label: 'Naik Nayak Nayaka' },
    { value: 'nair', label: 'Nair' },
    { value: 'nair_adiyodi', label: 'Nair-Adiyodi' },
    { value: 'nair_anthur', label: 'Nair-Anthur' },
    { value: 'nair_chekkala_nair', label: 'Nair-Chekkala Nair' },
    { value: 'nair_illam', label: 'Nair-Illam' },
    { value: 'nair_kaimal', label: 'Nair-Kaimal' },
    { value: 'nair_kartha', label: 'Nair-Kartha' },
    { value: 'nair_kiryathil', label: 'Nair-Kiryathil' },
    { value: 'nair_kurup', label: 'Nair-Kurup' },
    { value: 'nair_maniyani', label: 'Nair-Maniyani' },
    { value: 'nair_mannadiar', label: 'Nair-Mannadiar' },
    { value: 'nair_marar', label: 'Nair-Marar' },
    { value: 'nair_menon', label: 'Nair-Menon' },
    { value: 'nair_nair_all', label: 'Nair-Nair All' },
    { value: 'nair_nair_vaniya', label: 'Nair-Nair-Vaniya' },
    { value: 'nair_nambiar', label: 'Nair-Nambiar' },
    { value: 'nair_panicker', label: 'Nair-Panicker' },
    { value: 'nair_pillai', label: 'Nair-Pillai' },
    { value: 'nair_poduval', label: 'Nair-Poduval' },
    { value: 'nair_thampi', label: 'Nair-Thampi' },
    { value: 'nair_tharakan', label: 'Nair-Tharakan' },
    { value: 'nair_unnithan', label: 'Nair-Unnithan' },
    { value: 'nair_vellala_pillai', label: 'Nair-Vellala Pillai' },
    { value: 'nair_veluthedathu', label: 'Nair-Veluthedathu' },
    { value: 'nair_vilakkithala', label: 'Nair-Vilakkithala' },
    { value: 'nair_veluthedathu', label: 'Nair Veluthedathu' },
    { value: 'nair_vilakkithala', label: 'Nair Vilakkithala' },
    { value: 'namasudra_namosudra', label: 'Namasudra / Namosudra' },
    { value: 'nambiar', label: 'Nambiar' },
    { value: 'nambisan', label: 'Nambisan' },
    { value: 'namboodiri', label: 'Namboodiri' },
    { value: 'namdev_chhipa', label: 'Namdev Chhipa' },
    { value: 'nandiwale', label: 'Nandiwale' },
    { value: 'napit', label: 'Napit' },
    { value: 'nath_jogi', label: 'Nath Jogi' },
    { value: 'nayee_barber', label: 'Nayee (Barber)' },
    { value: 'nepali', label: 'Nepali' },
    { value: 'nessi_kurni', label: 'Nessi / Kurni' },
    { value: 'nhavi', label: 'Nhavi' },
    { value: 'nonia', label: 'Nonia' },
    { value: 'obc', label: 'OBC' },
    { value: 'odan', label: 'Odan' },
    { value: 'oraon', label: 'Oraon' },
    { value: 'oswal', label: 'Oswal' },
    { value: 'otari', label: 'Otari' },
    { value: 'others', label: 'Others' },
    { value: 'padmashali', label: 'Padmashali' },
    { value: 'padmashali_devanga', label: 'Padmashali-Devanga' },
    { value: 'padmashali_jaandra', label: 'Padmashali-Jaandra' },
    { value: 'padmashali_kaikaala', label: 'Padmashali-Kaikaala' },
    { value: 'padmashali_karakala_bhakthula', label: 'Padmashali-Karakala Bhakthula' },
    { value: 'padmashali_karni_bhakthula', label: 'Padmashali-Karni Bhakthula' },
    { value: 'padmashali_kurni', label: 'Padmashali-Kurni' },
    { value: 'padmashali_neeli_saali', label: 'Padmashali-Neeli Saali' },
    { value: 'padmashali_nessi', label: 'Padmashali-Nessi' },
    { value: 'padmashali_pattusali', label: 'Padmashali-Pattusali' },
    { value: 'padmashali_shettigar', label: 'Padmashali-Shettigar' },
    { value: 'padmashali_swakula_saali', label: 'Padmashali-Swakula Saali' },
    { value: 'padmashali_thogata_veerakshathriya', label: 'Padmashali-Thogata Veerakshathriya' },
    { value: 'pal', label: 'Pal' },
    { value: 'panan', label: 'Panan' },
    { value: 'panchal', label: 'Panchal' },
    { value: 'panchamsali', label: 'Panchamsali' },
    { value: 'pandaram', label: 'Pandaram' },
    { value: 'panicker', label: 'Panicker' },
    { value: 'pano', label: 'Pano' },
    { value: 'paravan_bhartar', label: 'Paravan Bhartar' },
    { value: 'parkava_kulam', label: 'Parkava Kulam' },
    { value: 'parvatha_rajakulam', label: 'Parvatha Rajakulam' },
    { value: 'pasi', label: 'Pasi' },
    { value: 'paswan_dusadh', label: 'Paswan / Dusadh' },
    { value: 'scheduled_tribe_all', label: 'Scheduled Tribe All' },
    { value: 'patel', label: 'Patel' },
    { value: 'patel_anjana_chowdary_patel', label: 'Patel-Anjana (Chowdary) Patel' },
    { value: 'patel_desai', label: 'Patel-Desai' },
    { value: 'patel_dodia', label: 'Patel-Dodia' },
    { value: 'patel_kadava_patel', label: 'Patel-Kadava Patel' },
    { value: 'patel_leva_patel', label: 'Patel-Leva Patel' },
    { value: 'patel_matia_patel', label: 'Patel-Matia Patel' },
    { value: 'patel_patel_desai', label: 'Patel-Patel Desai' },
    { value: 'patel_dodia', label: 'patel Dodia' },
    { value: 'patel_kadva', label: 'patel Kadva' },
    { value: 'patel_leva', label: 'patel Leva' },
    { value: 'patel_leva_27_gam', label: 'patel Leva-27 Gam' },
    { value: 'patel_leva_baavis_gam', label: 'patel Leva-Baavis Gam' },
    { value: 'patel_leva_chaa_gam', label: 'patel Leva-Chaa Gam' },
    { value: 'patel_leva_chovis_gam', label: 'patel Leva-Chovis Gam' },
    { value: 'patel_leva_mota_sattavi', label: 'patel Leva-Mota Sattavi' },
    { value: 'patel_leva_nani_sattavi', label: 'patel Leva-Nani Sattavi' },
    { value: 'patel_leva_panch_gam', label: 'patel Leva-Panch Gam' },
    { value: 'patel_lodhi', label: 'Patel Lodhi' },
    { value: 'pathare_prabhu', label: 'Pathare Prabhu' },
    { value: 'patnaick', label: 'Patnaick' },
    { value: 'patra', label: 'Patra' },
    { value: 'perika', label: 'Perika' },
    { value: 'pillai', label: 'Pillai' },
    { value: 'pillai_aaru_nattu_vellala', label: 'Pillai-Aaru Nattu Vellala' },
    { value: 'pillai_agamudayar_arcot_thuluva_vellala', label: 'Pillai-Agamudayar/Arcot/Thuluva Vellala' },
    { value: 'pillai_cherakula_vellalar', label: 'Pillai-Cherakula Vellalar' },
    { value: 'pillai_desikar', label: 'Pillai-Desikar' },
    { value: 'pillai_desikar_thanjavur', label: 'Pillai-Desikar Thanjavur' },
    { value: 'pillai_illaththu_pillai', label: 'Pillai-Illaththu Pillai' },
    { value: 'pillai_isai_vellalar', label: 'Pillai-Isai Vellalar' },
    { value: 'pillai_karkathar', label: 'Pillai-Karkathar' },
    { value: 'pillai_kodikal_pillai', label: 'Pillai-Kodikal Pillai' },
    { value: 'pillai_nanjil', label: 'Pillai-Nanjil' },
    { value: 'pillai_nanjil_mudali', label: 'Pillai-Nanjil Mudali' },
    { value: 'pillai_nankudi_vellalar', label: 'Pillai-Nankudi Vellalar' },
    { value: 'pillai_othuvaar', label: 'Pillai-Othuvaar' },
    { value: 'pillai_pandiya_vellalar', label: 'Pillai-Pandiya Vellalar' },
    { value: 'pillai_saiva_pillai_thanjavur', label: 'Pillai-Saiva Pillai Thanjavur' },
    { value: 'pillai_saiva_pillai_tirunelvi', label: 'Pillai-Saiva Pillai Tirunelvi' },
    { value: 'pillai_sengunthar_kaikolar', label: 'Pillai-Sengunthar/Kaikolar' },
    { value: 'pillai_sozhiya_vellalar', label: 'Pillai-Sozhiya Vellalar' },
    { value: 'pillai_thondai_mandala_vellala', label: 'Pillai-Thondai Mandala Vellala' },
    { value: 'pillai_veerakodi_vellala', label: 'Pillai-Veerakodi Vellala' },
    { value: 'pillai_vellala_pillai', label: 'Pillai-Vellala Pillai' },
    { value: 'pollon_devandra_kula_vellalan', label: 'Pollon Devandra Kula Vellalan' },
    { value: 'ponan', label: 'Ponan' },
    { value: 'poosala', label: 'Poosala' },
    { value: 'poundra', label: 'Poundra' },
    { value: 'prajapati', label: 'Prajapati' },
    { value: 'pulaya_chruman', label: 'Pulaya Chruman' },
    { value: 'rabari', label: 'Rabari' },
    { value: 'raigar', label: 'Raigar' },
    { value: 'raikwar', label: 'Raikwar' },
    { value: 'rajaka', label: 'Rajaka' },
    { value: 'rajaka_rajaka_vannar', label: 'Rajaka-Rajaka Vannar' },
    { value: 'rajbhar', label: 'Rajbhar' },
    { value: 'rajbongshi', label: 'Rajbongshi' },
    { value: 'rajpurohit', label: 'Rajpurohit' },
    { value: 'rajput', label: 'Rajput' },
    { value: 'rajput_aheria_rajput', label: 'Rajput-Aheria Rajput' },
    { value: 'rajput_baghel', label: 'Rajput-Baghel' },
    { value: 'rajput_bais', label: 'Rajput-Bais' },
    { value: 'rajput_bankawat', label: 'Rajput-Bankawat' },
    { value: 'rajput_bargujar', label: 'Rajput-Bargujar' },
    { value: 'rajput_bhadauria', label: 'Rajput-Bhadauria' },
    { value: 'rajput_bharbhunja', label: 'Rajput-Bharbhunja' },
    { value: 'rajput_bhatti', label: 'Rajput-Bhatti' },
    { value: 'rajput_bhriguvansha', label: 'Rajput-Bhriguvansha' },
    { value: 'rajput_bisen', label: 'Rajput-Bisen' },
    { value: 'rajput_bisht', label: 'Rajput-Bisht' },
    { value: 'rajput_chandel', label: 'Rajput-Chandel' },
    { value: 'rajput_chandravanshi', label: 'Rajput-Chandravanshi' },
    { value: 'rajput_chandrawat', label: 'Rajput-Chandrawat' },
    { value: 'rajput_chauhan', label: 'Rajput-Chauhan' },
    { value: 'rajput_chawda_chavada', label: 'Rajput-Chawda / Chavada' },
    { value: 'rajput_chib', label: 'Rajput-Chib' },
    { value: 'rajput_chundawat', label: 'Rajput-Chundawat' },
    { value: 'rajput_dhakare', label: 'Rajput-Dhakare' },
    { value: 'rajput_dixit', label: 'Rajput-Dixit' },
    { value: 'rajput_doad', label: 'Rajput-Doad' },
    { value: 'rajput_dogra', label: 'Rajput-Dogra' },
    { value: 'rajput_durgavanshi', label: 'Rajput-Durgavanshi' },
    { value: 'rajput_gahlot', label: 'Rajput-Gahlot' },
    { value: 'rajput_garhwal', label: 'Rajput-Garhwal' },
    { value: 'rajput_gautam', label: 'Rajput-Gautam' },
    { value: 'rajput_gogawat', label: 'Rajput-Gogawat' },
    { value: 'rajput_gohil', label: 'Rajput-Gohil' },
    { value: 'rajput_goud_gaur', label: 'Rajput-Goud / Gaur' },
    { value: 'rajput_jadeja', label: 'Rajput-Jadeja' },
    { value: 'rajput_jadon', label: 'Rajput-Jadon' },
    { value: 'rajput_jamwal', label: 'Rajput-Jamwal' },
    { value: 'rajput_janjua', label: 'Rajput-Janjua' },
    { value: 'rajput_jasrotia', label: 'Rajput-Jasrotia' },
    { value: 'rajput_jaswal', label: 'Rajput-Jaswal' },
    { value: 'rajput_jhala', label: 'Rajput-Jhala' },
    { value: 'rajput_kachwaha', label: 'Rajput-Kachwaha' },
    { value: 'rajput_kalyat', label: 'Rajput-Kalyat' },
    { value: 'rajput_katoch', label: 'Rajput-Katoch' },
    { value: 'rajput_kaushik', label: 'Rajput-Kaushik' },
    { value: 'rajput_khadagvanshi_khagi', label: 'Rajput-Khadagvanshi Khagi' },
    { value: 'rajput_khangarot', label: 'Rajput-Khangarot' },
    { value: 'rajput_khati', label: 'Rajput-Khati' },
    { value: 'rajput_kirar', label: 'Rajput-Kirar' },
    { value: 'rajput_kumaoni', label: 'Rajput-Kumaoni' },
    { value: 'rajput_kuruvanshi', label: 'Rajput-Kuruvanshi' },
    { value: 'rajput_kushwaha', label: 'Rajput-Kushwaha' },
    { value: 'rajput_lodhi_rajput', label: 'Rajput-Lodhi Rajput' },
    { value: 'rajput_loniya_lonia_lunia', label: 'Rajput-Loniya Lonia Lunia' },
    { value: 'rajput_madad', label: 'Rajput-Madad' },
    { value: 'rajput_mahror', label: 'Rajput-Mahror' },
    { value: 'rajput_mahthan', label: 'Rajput-Mahthan' },
    { value: 'rajput_mahyavanshi', label: 'Rajput-Mahyavanshi' },
    { value: 'rajput_manhas', label: 'Rajput-Manhas' },
    { value: 'rajput_nagvanshi', label: 'Rajput-Nagvanshi' },
    { value: 'rajput_naruka', label: 'Rajput-Naruka' },
    { value: 'rajput_nathawat', label: 'Rajput-Nathawat' },
    { value: 'rajput_negi', label: 'Rajput-Negi' },
    { value: 'rajput_nikumbh', label: 'Rajput-Nikumbh' },
    { value: 'rajput_oad_rajput', label: 'Rajput-Oad Rajput' },
    { value: 'rajput_parihar', label: 'Rajput-Parihar' },
    { value: 'rajput_parmar', label: 'Rajput-Parmar' },
    { value: 'rajput_pratihar', label: 'Rajput-Pratihar' },
    { value: 'rajput_pundir', label: 'Rajput-Pundir' },
    { value: 'rajput_raghuvanshi', label: 'Rajput-Raghuvanshi' },
    { value: 'rajput_rajawal', label: 'Rajput-Rajawal' },
    { value: 'rajput_rajput_swarnkar', label: 'Rajput-Rajput Swarnkar' },
    { value: 'rajput_rana', label: 'Rajput-Rana' },
    { value: 'rajput_rao', label: 'Rajput-Rao' },
    { value: 'rajput_rathore', label: 'Rajput-Rathore' },
    { value: 'rajput_rawa_rajput', label: 'Rajput-Rawa Rajput' },
    { value: 'rajput_rawal', label: 'Rajput-Rawal' },
    { value: 'rajput_rohilla', label: 'Rajput-Rohilla' },
    { value: 'rajput_sagar_rajput', label: 'Rajput-Sagar Rajput' },
    { value: 'rajput_sainthwar_rajput', label: 'Rajput-Sainthwar Rajput' },
    { value: 'rajput_sarangdevot', label: 'Rajput-Sarangdevot' },
    { value: 'rajput_shakya', label: 'Rajput-Shakya' },
    { value: 'rajput_shekhawat', label: 'Rajput-Shekhawat' },
    { value: 'rajput_sikarwar', label: 'Rajput-Sikarwar' },
    { value: 'rajput_singh', label: 'Rajput-Singh' },
    { value: 'rajput_sisodia', label: 'Rajput-Sisodia' },
    { value: 'rajput_solanki', label: 'Rajput-Solanki' },
    { value: 'rajput_somvansha', label: 'Rajput-Somvansha' },
    { value: 'rajput_surwar', label: 'Rajput-Surwar' },
    { value: 'rajput_suryavanshi', label: 'Rajput-Suryavanshi' },
    { value: 'rajput_tanwar', label: 'Rajput-Tanwar' },
    { value: 'rajput_thakur', label: 'Rajput-Thakur' },
    { value: 'rajput_tomar', label: 'Rajput-Tomar' },
    { value: 'rajput_ujjain', label: 'Rajput-Ujjain' },
    { value: 'rajput_vaishhya', label: 'Rajput-Vaishhya' },
    { value: 'rajput_garhwali', label: 'Rajput Garhwali' },
    { value: 'rajput_kumaoni', label: 'Rajput Kumaoni' },
    { value: 'rajput_rohella_tank', label: 'Rajput Rohella Tank' },
    { value: 'ramdasia', label: 'Ramdasia' },
    { value: 'ramgarhia', label: 'Ramgarhia' },
    { value: 'ramoshi_berad_bedar', label: 'Ramoshi Berad Bedar' },
    { value: 'ravidasia', label: 'Ravidasia' },
    { value: 'rawat', label: 'Rawat' },
    { value: 'reddy', label: 'Reddy' },
    { value: 'reddy_ayodhi', label: 'Reddy-Ayodhi' },
    { value: 'reddy_bhoomanchi_reddy', label: 'Reddy-Bhoomanchi Reddy' },
    { value: 'reddy_chowdary', label: 'Reddy-Chowdary' },
    { value: 'reddy_desuru', label: 'Reddy-Desuru' },
    { value: 'reddy_gandla', label: 'Reddy-Gandla' },
    { value: 'reddy_ganjam', label: 'Reddy-Ganjam' },
    { value: 'reddy_gone_kapu', label: 'Reddy-Gone Kapu' },
    { value: 'reddy_gudati', label: 'Reddy-Gudati' },
    { value: 'reddy_kapu', label: 'Reddy-Kapu' },
    { value: 'reddy_motati', label: 'Reddy-Motati' },
    { value: 'reddy_palle', label: 'Reddy-Palle' },
    { value: 'reddy_palnati', label: 'Reddy-Palnati' },
    { value: 'reddy_panta', label: 'Reddy-Panta' },
    { value: 'reddy_pedakanti', label: 'Reddy-Pedakanti' },
    { value: 'reddy_poknati', label: 'Reddy-Poknati' },
    { value: 'reddy_reddiar', label: 'Reddy-Reddiar' },
    { value: 'reddy_sajjana', label: 'Reddy-Sajjana' },
    { value: 'reddy_vanni', label: 'Reddy-Vanni' },
    { value: 'reddy_velanati', label: 'Reddy-Velanati' },
    { value: 'relli', label: 'Relli' },
    { value: 'rohit_chamar', label: 'Rohit Chamar' },
    { value: 'ror', label: 'Ror' },
    { value: 'sadgope', label: 'Sadgope' },
    { value: 'saha', label: 'Saha' },
    { value: 'sahu', label: 'Sahu' },
    { value: 'saini', label: 'Saini' },
    { value: 'saliya', label: 'Saliya' },
    { value: 'samagar', label: 'Samagar' },
    { value: 'sambava', label: 'Sambava' },
    { value: 'santhali', label: 'Santhali' },
    { value: 'sargara', label: 'Sargara' },
    { value: 'sathwara', label: 'Sathwara' },
    { value: 'satnami', label: 'Satnami' },
    { value: 'savji', label: 'Savji' },
    { value: 'sawantwadi', label: 'Sawantwadi' },
    { value: 'scheduled_caste', label: 'Scheduled Caste' },
    { value: 'scheduled_tribe', label: 'Scheduled Tribe' },
    { value: 'senai_thalaivar', label: 'Senai Thalaivar' },
    { value: 'senguntha_mudaliyar', label: 'Senguntha Mudaliyar' },
    { value: 'settibalija', label: 'Settibalija' },
    { value: 'shah', label: 'Shah' },
    { value: 'shilpkar', label: 'Shilpkar' },
    { value: 'shimpi', label: 'Shimpi' },
    { value: 'silawat', label: 'Silawat' },
    { value: 'sillekyatha', label: 'Sillekyatha' },
    { value: 'sindhi', label: 'Sindhi' },
    { value: 'sindhi_sindhi_amil', label: 'Sindhi-Sindhi Amil' },
    { value: 'sindhi_sindhi_baibhand', label: 'Sindhi-Sindhi Baibhand' },
    { value: 'sindhi_sindhi_bhanusali', label: 'Sindhi-Sindhi Bhanusali' },
    { value: 'sindhi_sindhi_bhatia', label: 'Sindhi-Sindhi Bhatia' },
    { value: 'sindhi_sindhi_chhapru', label: 'Sindhi-Sindhi Chhapru' },
    { value: 'sindhi_sindhi_daru', label: 'Sindhi-Sindhi Daru' },
    { value: 'sindhi_sindhi_hydrabadi', label: 'Sindhi-Sindhi Hydrabadi' },
    { value: 'sindhi_sindhi_larai', label: 'Sindhi-Sindhi Larai' },
    { value: 'sindhi_sindhi_larkan', label: 'Sindhi-Sindhi Larkan' },
    { value: 'sindhi_sindhi_larkana', label: 'Sindhi-Sindhi Larkana' },
    { value: 'sindhi_sindhi_lohana', label: 'Sindhi-Sindhi Lohana' },
    { value: 'sindhi_sindhi_rohiri', label: 'Sindhi-Sindhi Rohiri' },
    { value: 'sindhi_sindhi_sahiti', label: 'Sindhi-Sindhi Sahiti' },
    { value: 'sindhi_sindhi_sakkhar', label: 'Sindhi-Sindhi Sakkhar' },
    { value: 'sindhi_sindhi_sehwani', label: 'Sindhi-Sindhi Sehwani' },
    { value: 'sindhi_sindhi_shikarpuri', label: 'Sindhi-Sindhi Shikarpuri' },
    { value: 'sindhi_sindhi_thatai', label: 'Sindhi-Sindhi Thatai' },
    { value: 'siyal', label: 'Siyal' },
    { value: 'skp', label: 'SKP' },
    { value: 'somvanshi', label: 'Somvanshi' },
    { value: 'somvanshi_kayastha_prabhu', label: 'Somvanshi Kayastha Prabhu' },
    { value: 'sonar_sunar', label: 'Sonar / Sunar' },
    { value: 'sonkar', label: 'Sonkar' },
    { value: 'sourashtra', label: 'Sourashtra' },
    { value: 'sozhiya_vellalar', label: 'Sozhiya Vellalar' },
    { value: 'srisayani', label: 'Srisayani' },
    { value: 'ssk', label: 'SSK' },
    { value: 'subarna_banik', label: 'Subarna Banik' },
    { value: 'sudi_suri_sundhi_shaundik', label: 'Sudi Suri Sundhi Shaundik' },
    { value: 'sugali_naika', label: 'Sugali (Naika)' },
    { value: 'sutar', label: 'Sutar' },
    { value: 'swakula_sali', label: 'Swakula sali' },
    { value: 'swarnkar', label: 'Swarnkar' },
    { value: 'tamboli', label: 'Tamboli' },
    { value: 'tammali', label: 'Tammali' },
    { value: 'tanti', label: 'Tanti' },
    { value: 'tantuway', label: 'Tantuway' },
    { value: 'telaga', label: 'Telaga' },
    { value: 'teli', label: 'Teli' },
    { value: 'thachar', label: 'Thachar' },
    { value: 'thakkar', label: 'Thakkar' },
    { value: 'thandan', label: 'Thandan' },
    { value: 'tharakan', label: 'Tharakan' },
    { value: 'thevar_mukkulathor', label: 'Thevar Mukkulathor' },
    { value: 'thevar_mukkulathor_agamudayar', label: 'Thevar Mukkulathor-Agamudayar' },
    { value: 'thevar_mukkulathor_ambalakarar', label: 'Thevar Mukkulathor-Ambalakarar' },
    { value: 'thevar_mukkulathor_appanad_kondayamkottai_maravar', label: 'Thevar Mukkulathor-Appanad Kondayamkottai Maravar' },
    { value: 'thevar_mukkulathor_easanattu_kallar', label: 'Thevar Mukkulathor-Easanattu Kallar' },
    { value: 'thevar_mukkulathor_kallar', label: 'Thevar Mukkulathor-Kallar' },
    { value: 'thevar_mukkulathor_maniyakarar', label: 'Thevar Mukkulathor-Maniyakarar' },
    { value: 'thevar_mukkulathor_maravar', label: 'Thevar Mukkulathor-Maravar' },
    { value: 'thevar_mukkulathor_piramalai_kallar', label: 'Thevar Mukkulathor-Piramalai Kallar' },
    { value: 'thevar_mukkulathor_rajakula_agamudayar', label: 'Thevar Mukkulathor-Rajakula Agamudayar' },
    { value: 'thevar_mukkulathor_sembanad_maravar', label: 'Thevar Mukkulathor-Sembanad Maravar' },
    { value: 'thevar_mukkulathor_servai', label: 'Thevar Mukkulathor-Servai' },
    { value: 'thevar_mukkulathor_thanjavur_kallar', label: 'Thevar Mukkulathor-Thanjavur Kallar' },
    { value: 'thevar_mukkulathor_vallambar', label: 'Thevar Mukkulathor-Vallambar' },
    { value: 'thigala', label: 'Thigala' },
    { value: 'thiyya', label: 'Thiyya' },
    { value: 'thiyya_ezhava', label: 'Thiyya-Ezhava' },
    { value: 'thiyya_kavuthiya', label: 'Thiyya-Kavuthiya' },
    { value: 'thiyya_thiyya_thandan', label: 'Thiyya-Thiyya Thandan' },
    { value: 'tili', label: 'Tili' },
    { value: 'togata', label: 'Togata' },
    { value: 'tonk_kshatriya', label: 'Tonk Kshatriya' },
    { value: 'tribe', label: 'Tribe' },
    { value: 'turi', label: 'Turi' },
    { value: 'turupu_kapu', label: 'Turupu Kapu' },
    { value: 'uppara', label: 'Uppara' },
    { value: 'vadar', label: 'Vadar' },
    { value: 'vaddera', label: 'Vaddera' },
    { value: 'vaduka', label: 'Vaduka' },
    { value: 'vaidiki_velanadu', label: 'Vaidiki Velanadu' },
    { value: 'vaish', label: 'Vaish' },
    { value: 'vaish_vaish_dhaneshawat', label: 'Vaish-Vaish Dhaneshawat' },
    { value: 'vaishnav', label: 'Vaishnav' },
    { value: 'vaishnav_bairagi_swami', label: 'Vaishnav-Bairagi Swami' },
    { value: 'vaishnav_vaishnav_bhatia', label: 'Vaishnav-Vaishnav Bhatia' },
    { value: 'vaishnav_vaishnav_dishaval', label: 'Vaishnav-Vaishnav Dishaval' },
    { value: 'vaishnav_vaishnav_kapol', label: 'Vaishnav-Vaishnav Kapol' },
    { value: 'vaishnav_vaishnav_khadyata', label: 'Vaishnav-Vaishnav Khadyata' },
    { value: 'vaishnav_vaishnav_lad', label: 'Vaishnav-Vaishnav Lad' },
    { value: 'vaishnav_vaishnav_modh', label: 'Vaishnav-Vaishnav Modh' },
    { value: 'vaishnav_vaishnav_porvad', label: 'Vaishnav-Vaishnav Porvad' },
    { value: 'vaishnav_vaishnav_shrimali', label: 'Vaishnav-Vaishnav Shrimali' },
    { value: 'vaishnav_vaishnav_sorathaiya', label: 'Vaishnav-Vaishnav Sorathaiya' },
    { value: 'vaishnav_vaishnav_vania', label: 'Vaishnav-Vaishnav Vania' },
    { value: 'vaishnav_vanik', label: 'Vaishnav Vanik' },
    { value: 'vaishnava', label: 'Vaishnava' },
    { value: 'vaishnava_brahmin_sri_vaishnava', label: 'Vaishnava-Brahmin Sri Vaishnava' },
    { value: 'vaishnava_chhatada_sri_vaishnava', label: 'Vaishnava-Chhatada Sri Vaishnava' },
    { value: 'vaishnava_sri_vaishnava', label: 'Vaishnava-Sri Vaishnava' },
    { value: 'vaishya', label: 'Vaishya' },
    { value: 'vaishya_mahuri', label: 'Vaishya-Mahuri' },
    { value: 'vaishya_mathur_vaishya', label: 'Vaishya-Mathur Vaishya' },
    { value: 'vaishya_vani', label: 'Vaishya Vani' },
    { value: 'vallala', label: 'Vallala' },
    { value: 'valluvar', label: 'Valluvar' },
    { value: 'valmiki', label: 'Valmiki' },
    { value: 'valuvan', label: 'Valuvan' },
    { value: 'vania', label: 'Vania' },
    { value: 'vaniya', label: 'Vaniya' },
    { value: 'vaniya_nair_vaniya', label: 'Vaniya-Nair-Vaniya' },
    { value: 'vaniya_vaniya_chettiar', label: 'Vaniya-Vaniya Chettiar' },
    { value: 'vanjara', label: 'Vanjara' },
    { value: 'vanjari', label: 'Vanjari' },
    { value: 'vankar', label: 'Vankar' },
    { value: 'vannar', label: 'Vannar' },
    { value: 'vannia_kula_kshatriyar', label: 'Vannia Kula Kshatriyar' },
    { value: 'vannia_kula_kshatriyar_arasu', label: 'Vannia Kula Kshatriyar-Arasu' },
    { value: 'vannia_kula_kshatriyar_gounder', label: 'Vannia Kula Kshatriyar-Gounder' },
    { value: 'vannia_kula_kshatriyar_naicker', label: 'Vannia Kula Kshatriyar-Naicker' },
    { value: 'vannia_kula_kshatriyar_padayachi', label: 'Vannia Kula Kshatriyar-Padayachi' },
    { value: 'vannia_kula_kshatriyar_palli', label: 'Vannia Kula Kshatriyar-Palli' },
    { value: 'vannia_kula_kshatriyar_pandal', label: 'Vannia Kula Kshatriyar-Pandal' },
    { value: 'vannia_kula_kshatriyar_urs', label: 'Vannia Kula Kshatriyar-Urs' },
    { value: 'vannia_kula_kshatriyar_vannia_reddiar', label: 'Vannia Kula Kshatriyar-Vannia Reddiar' },
    { value: 'vannia_kula_kshatriyar_vanniyar', label: 'Vannia Kula Kshatriyar-Vanniyar' },
    { value: 'vanniyar', label: 'Vanniyar' },
    { value: 'variar', label: 'Variar' },
    { value: 'varshney', label: 'Varshney' },
    { value: 'veershaiva_veera_saivam', label: 'Veershaiva Veera Saivam' },
    { value: 'velaan', label: 'Velaan' },
    { value: 'velama', label: 'Velama' },
    { value: 'velama_adivelama', label: 'Velama-Adivelama' },
    { value: 'velama_koppula', label: 'Velama-Koppula' },
    { value: 'velama_padmanayaka', label: 'Velama-Padmanayaka' },
    { value: 'velama_polinati', label: 'Velama-Polinati' },
    { value: 'velama_yellapa', label: 'Velama-Yellapa' },
    { value: 'velan', label: 'Velan' },
    { value: 'vellalar', label: 'Vellalar' },
    { value: 'vellalar_aaru_nattu_vellala', label: 'Vellalar-Aaru Nattu Vellala' },
    { value: 'vellalar_agamudayar_arcot_thuluva_vellala', label: 'Vellalar-Agamudayar/Arcot/Thuluva Vellala' },
    { value: 'vellalar_cherakula_vellalar', label: 'Vellalar-Cherakula Vellalar' },
    { value: 'vellalar_desikar', label: 'Vellalar-Desikar' },
    { value: 'vellalar_devendra_kula_vellalar', label: 'Vellalar-Devendra Kula Vellalar' },
    { value: 'vellalar_illaththu_pillai', label: 'Vellalar-Illaththu Pillai' },
    { value: 'vellalar_isai_vellalar', label: 'Vellalar-Isai Vellalar' },
    { value: 'vellalar_karkathar', label: 'Vellalar-Karkathar' },
    { value: 'vellalar_kodikal_pillai', label: 'Vellalar-Kodikal Pillai' },
    { value: 'vellalar_kongu_vellala_gounder', label: 'Vellalar-Kongu Vellala Gounder' },
    { value: 'vellalar_nanjil_mudali', label: 'Vellalar-Nanjil Mudali' },
    { value: 'vellalar_nanjil_nattu_vellalar', label: 'Vellalar-Nanjil Nattu Vellalar' },
    { value: 'vellalar_nanjil_vellalar', label: 'Vellalar-Nanjil Vellalar' },
    { value: 'vellalar_nankudi_vellalar', label: 'Vellalar-Nankudi Vellalar' },
    { value: 'vellalar_othuvaar', label: 'Vellalar-Othuvaar' },
    { value: 'vellalar_pandiya_vellalar', label: 'Vellalar-Pandiya Vellalar' },
    { value: 'vellalar_saiva_pillai_thanjavur', label: 'Vellalar-Saiva Pillai Thanjavur' },
    { value: 'vellalar_saiva_pillai_tirunelveli', label: 'Vellalar-Saiva Pillai Tirunelveli' },
    { value: 'vellalar_saiva_vellalar', label: 'Vellalar-Saiva Vellalar' },
    { value: 'vellalar_sengunthar_kaikolar', label: 'Vellalar-Sengunthar/Kaikolar' },
    { value: 'vellalar_sozhiya_vellalar', label: 'Vellalar-Sozhiya Vellalar' },
    { value: 'vellalar_thondai_mandala_vellala', label: 'Vellalar-Thondai Mandala Vellala' },
    { value: 'vellalar_veerakodi', label: 'Vellalar-Veerakodi' },
    { value: 'vellalar_vellalar_all', label: 'Vellalar-Vellalar All' },
    { value: 'vettuva_gounder', label: 'Vettuva Gounder' },
    { value: 'vettuvan', label: 'Vettuvan' },
    { value: 'vishwakarma', label: 'Vishwakarma' },
    { value: 'vishwakarma_black_smith', label: 'Vishwakarma-Black Smith' },
    { value: 'vishwakarma_carpentry_vadrangi_vadla', label: 'Vishwakarma-Carpentry (Vadrangi, Vadla)' },
    { value: 'vishwakarma_goldsmiths', label: 'Vishwakarma-Goldsmiths' },
    { value: 'vishwakarma_sculptor_shilpi', label: 'Vishwakarma-Sculptor (Shilpi)' },
    { value: 'vokkaliga', label: 'Vokkaliga' },
    { value: 'vysya', label: 'Vysya' },
    { value: 'wani', label: 'Wani' },
    { value: 'yadav_yadava', label: 'Yadav / Yadava' },
    { value: 'yadav_yadava_aheer_ahir', label: 'Yadav / Yadava-Aheer / Ahir' },
    { value: 'yadav_yadava_ala_golla', label: 'Yadav / Yadava-Ala Golla' },
    { value: 'yadav_yadava_daddi', label: 'Yadav / Yadava-Daddi' },
    { value: 'yadav_yadava_das', label: 'Yadav / Yadava-Das' },
    { value: 'yadav_yadava_dhador', label: 'Yadav / Yadava-Dhador' },
    { value: 'yadav_yadava_erragola', label: 'Yadav / Yadava-Erragola' },
    { value: 'yadav_yadava_gadri_gadariya', label: 'Yadav / Yadava-Gadri / Gadariya' },
    { value: 'yadav_yadava_gauda', label: 'Yadav / Yadava-Gauda' },
    { value: 'yadav_yadava_gawli', label: 'Yadav / Yadava-Gawli' },
    { value: 'yadav_yadava_goal_gola_golla', label: 'Yadav / Yadava-Goal / Gola / Golla' },
    { value: 'yadav_yadava_gop_gopal_gopala', label: 'Yadav / Yadava-Gop / Gopal / Gopala' },
    { value: 'yadav_yadava_goriya', label: 'Yadav / Yadava-Goriya' },
    { value: 'yadav_yadava_gwala', label: 'Yadav / Yadava-Gwala' },
    { value: 'yadav_yadava_gwalvanshi', label: 'Yadav / Yadava-Gwalvanshi' },
    { value: 'yadav_yadava_jadav', label: 'Yadav / Yadava-Jadav' },
    { value: 'yadav_yadava_kohar', label: 'Yadav / Yadava-Kohar' },
    { value: 'yadav_yadava_konar', label: 'Yadav / Yadava-Konar' },
    { value: 'yadav_yadava_korna', label: 'Yadav / Yadava-Korna' },
    { value: 'yadav_yadava_krishnauth', label: 'Yadav / Yadava-Krishnauth' },
    { value: 'yadav_yadava_kurudas_gollas', label: 'Yadav / Yadava-Kurudas Gollas' },
    { value: 'yadav_yadava_kuruma', label: 'Yadav / Yadava-Kuruma' },
    { value: 'yadav_yadava_mandal', label: 'Yadav / Yadava-Mandal' },
    { value: 'yadav_yadava_manjrauth', label: 'Yadav / Yadava-Manjrauth' },
    { value: 'yadav_yadava_nandvanshi', label: 'Yadav / Yadava-Nandvanshi' },
    { value: 'yadav_yadava_pakanati', label: 'Yadav / Yadava-Pakanati' },
    { value: 'yadav_yadava_puja', label: 'Yadav / Yadava-Puja' },
    { value: 'yadav_yadava_raut', label: 'Yadav / Yadava-Raut' },
    { value: 'yadav_yadava_suryavanshi', label: 'Yadav / Yadava-Suryavanshi' },
    { value: 'yadav_yadava_thethwar', label: 'Yadav / Yadava-Thethwar' },
    { value: 'yadav_yadava_yadav_golla', label: 'Yadav / Yadava-Yadav Golla' },
    { value: 'yadav_yadava_yaduvanshi', label: 'Yadav / Yadava-Yaduvanshi' },
    { value: 'yellapu', label: 'Yellapu' }
  ],
  muslim: [
    { value: 'shia', label: 'Shia' },
    { value: 'sunni', label: 'Sunni' },
    { value: 'other', label: 'Other' },
  ],
  christian: [
    { value: 'catholic', label: 'Catholic' },
    { value: 'protestant', label: 'Protestant' },
    { value: 'orthodox', label: 'Orthodox' },
    { value: 'other', label: 'Other' },
  ],
  sikh: [
    { value: 'jatt', label: 'Jatt' },
    { value: 'other', label: 'Other' },
  ],
  jain: [
    { value: 'digambara', label: 'Digambara' },
    { value: 'svetambara', label: 'Svetambara' },
    { value: 'other', label: 'Other' },
  ],
  buddhist: [
    { value: 'theravada', label: 'Theravada' },
    { value: 'mahayana', label: 'Mahayana' },
    { value: 'vajrayana', label: 'Vajrayana' },
    { value: 'navayana', label: 'Navayana / Ambedkarite' },
    { value: 'other', label: 'Other' },
  ],
  parsi: [
    { value: 'zoroastrian', label: 'Zoroastrian' },
    { value: 'irani', label: 'Irani' },
    { value: 'other', label: 'Other' },
  ],
  jewish: [
    { value: 'bene_israel', label: 'Bene Israel' },
    { value: 'cochin', label: 'Cochin Jews' },
    { value: 'baghdadi', label: 'Baghdadi' },
    { value: 'ashkenazi', label: 'Ashkenazi' },
    { value: 'sephardi', label: 'Sephardi' },
    { value: 'other', label: 'Other' },
  ],
  // RELIGION_OPTIONS uses the key "other"; this list was only ever reachable as
  // "others". Both spellings are kept so neither lookup misses.
  other: [
    { value: 'other', label: 'Other' },
  ],
  others: [
    { value: 'other', label: 'Other' },
  ],
};

export const motherTongueOptions = [
                    { value: 'Hindi', label: 'Hindi' },
                    { value: 'Urdu', label: 'Urdu' },
                    { value: 'Punjabi', label: 'Punjabi' },
                    { value: 'Haryanvi', label: 'Haryanvi' },
                    { value: 'Marwari', label: 'Marwari' },
                    { value: 'Rajasthani', label: 'Rajasthani' },
                    { value: 'Tamil', label: 'Tamil' },
                    { value: 'Telugu', label: 'Telugu' },
                    { value: 'Kannada', label: 'Kannada' },
                    { value: 'Malayalam', label: 'Malayalam' },
                    { value: 'Bengali', label: 'Bengali' },
                    { value: 'Gujarati', label: 'Gujarati' },
                    { value: 'Marathi', label: 'Marathi' },
                    { value: 'Odia', label: 'Odia' },
                    { value: 'Assamese', label: 'Assamese' },
                    { value: 'Nepali', label: 'Nepali' },
                    { value: 'Bhojpuri', label: 'Bhojpuri' },
                    { value: 'Maithili', label: 'Maithili' },
                    { value: 'Sindhi', label: 'Sindhi' },
                    { value: 'Kashmiri', label: 'Kashmiri' },
                    { value: 'Dogri', label: 'Dogri' },
                    { value: 'Konkani', label: 'Konkani' },
                    { value: 'Manipuri', label: 'Manipuri' },
                    { value: 'Sanskrit', label: 'Sanskrit' },
                    { value: 'Other', label: 'Other' }, 
                  ];